name: flutter_piano
description: A Cross platform Midi Piano built with Flutter.
maintainer: Rody Davis Jr <rody.davis.jr@gmail.com>
homepage: https://github.com/rodydavis/flutter_piano
version: 2.0.0+500
publish_to: none
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_hooks: ^0.21.2
  get_it: ^8.0.2
  injectable: ^2.5.0
  go_router: ^14.7.2
  recase: ^4.1.0
  shared_preferences: ^2.3.2
  app_review: ^3.0.0
  audioplayers: ^5.2.1
  intl: any
  country_flags: ^3.0.0
  flutter_whatsnew: ^1.0.5+2
  shadcn_ui: ^0.53.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_version: ^2.1.1
  build_runner: ^2.4.9
  injectable_generator: ^2.6.2
  msix: ^3.16.1
  mocktail: ^1.0.4

dependency_overrides:
  package_info_plus: ^4.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/sounds/shot/
    - assets/sounds/sustain/
    - CHANGELOG.md
    - web/icons/Icon-192.png
