
var CanvasKitInit = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(moduleArg = {}) {

var r=moduleArg,aa,ca;r.ready=new Promise((a,b)=>{aa=a;ca=b});
(function(a){a.Id=a.Id||[];a.Id.push(function(){a.MakeSWCanvasSurface=function(b){var c=b,e="undefined"!==typeof OffscreenCanvas&&c instanceof OffscreenCanvas;if(!("undefined"!==typeof HTMLCanvasElement&&c instanceof HTMLCanvasElement||e||(c=document.getElementById(b),c)))throw"Canvas with id "+b+" was not found";if(b=a.MakeSurface(c.width,c.height))b.ie=c;return b};a.MakeCanvasSurface||(a.MakeCanvasSurface=a.MakeSWCanvasSurface);a.MakeSurface=function(b,c){var e={width:b,height:c,colorType:a.ColorType.RGBA_8888,
alphaType:a.AlphaType.Unpremul,colorSpace:a.ColorSpace.SRGB},f=b*c*4,k=a._malloc(f);if(e=a.Surface._makeRasterDirect(e,k,4*b))e.ie=null,e.Qe=b,e.Ne=c,e.Oe=f,e.te=k,e.getCanvas().clear(a.TRANSPARENT);return e};a.MakeRasterDirectSurface=function(b,c,e){return a.Surface._makeRasterDirect(b,c.byteOffset,e)};a.Surface.prototype.flush=function(b){a.Fd(this.Ed);this._flush();if(this.ie){var c=new Uint8ClampedArray(a.HEAPU8.buffer,this.te,this.Oe);c=new ImageData(c,this.Qe,this.Ne);b?this.ie.getContext("2d").putImageData(c,
0,0,b[0],b[1],b[2]-b[0],b[3]-b[1]):this.ie.getContext("2d").putImageData(c,0,0)}};a.Surface.prototype.dispose=function(){this.te&&a._free(this.te);this.delete()};a.Fd=a.Fd||function(){};a.je=a.je||function(){return null}})})(r);
(function(a){a.Id=a.Id||[];a.Id.push(function(){function b(m,q,x){return m&&m.hasOwnProperty(q)?m[q]:x}function c(m){var q=da(ea);ea[q]=m;return q}function e(m){return m.naturalHeight||m.videoHeight||m.displayHeight||m.height}function f(m){return m.naturalWidth||m.videoWidth||m.displayWidth||m.width}function k(m,q,x,y){m.bindTexture(m.TEXTURE_2D,q);y||x.alphaType!==a.AlphaType.Premul||m.pixelStorei(m.UNPACK_PREMULTIPLY_ALPHA_WEBGL,!0);return q}function l(m,q,x){x||q.alphaType!==a.AlphaType.Premul||
m.pixelStorei(m.UNPACK_PREMULTIPLY_ALPHA_WEBGL,!1);m.bindTexture(m.TEXTURE_2D,null)}a.GetWebGLContext=function(m,q){if(!m)throw"null canvas passed into makeWebGLContext";var x={alpha:b(q,"alpha",1),depth:b(q,"depth",1),stencil:b(q,"stencil",8),antialias:b(q,"antialias",0),premultipliedAlpha:b(q,"premultipliedAlpha",1),preserveDrawingBuffer:b(q,"preserveDrawingBuffer",0),preferLowPowerToHighPerformance:b(q,"preferLowPowerToHighPerformance",0),failIfMajorPerformanceCaveat:b(q,"failIfMajorPerformanceCaveat",
0),enableExtensionsByDefault:b(q,"enableExtensionsByDefault",1),explicitSwapControl:b(q,"explicitSwapControl",0),renderViaOffscreenBackBuffer:b(q,"renderViaOffscreenBackBuffer",0)};x.majorVersion=q&&q.majorVersion?q.majorVersion:"undefined"!==typeof WebGL2RenderingContext?2:1;if(x.explicitSwapControl)throw"explicitSwapControl is not supported";m=fa(m,x);if(!m)return 0;ha(m);w.Qd.getExtension("WEBGL_debug_renderer_info");return m};a.deleteContext=function(m){w===ia[m]&&(w=null);"object"==typeof JSEvents&&
JSEvents.uf(ia[m].Qd.canvas);ia[m]&&ia[m].Qd.canvas&&(ia[m].Qd.canvas.Ke=void 0);ia[m]=null};a._setTextureCleanup({deleteTexture:function(m,q){var x=ea[q];x&&ia[m].Qd.deleteTexture(x);ea[q]=null}});a.MakeWebGLContext=function(m){if(!this.Fd(m))return null;var q=this._MakeGrContext();if(!q)return null;q.Ed=m;var x=q.delete.bind(q);q["delete"]=function(){a.Fd(this.Ed);x()}.bind(q);return w.ve=q};a.MakeGrContext=a.MakeWebGLContext;a.GrDirectContext.prototype.getResourceCacheLimitBytes=function(){a.Fd(this.Ed);
this._getResourceCacheLimitBytes()};a.GrDirectContext.prototype.getResourceCacheUsageBytes=function(){a.Fd(this.Ed);this._getResourceCacheUsageBytes()};a.GrDirectContext.prototype.releaseResourcesAndAbandonContext=function(){a.Fd(this.Ed);this._releaseResourcesAndAbandonContext()};a.GrDirectContext.prototype.setResourceCacheLimitBytes=function(m){a.Fd(this.Ed);this._setResourceCacheLimitBytes(m)};a.MakeOnScreenGLSurface=function(m,q,x,y,B,D){if(!this.Fd(m.Ed))return null;q=void 0===B||void 0===D?
this._MakeOnScreenGLSurface(m,q,x,y):this._MakeOnScreenGLSurface(m,q,x,y,B,D);if(!q)return null;q.Ed=m.Ed;return q};a.MakeRenderTarget=function(){var m=arguments[0];if(!this.Fd(m.Ed))return null;if(3===arguments.length){var q=this._MakeRenderTargetWH(m,arguments[1],arguments[2]);if(!q)return null}else if(2===arguments.length){if(q=this._MakeRenderTargetII(m,arguments[1]),!q)return null}else return null;q.Ed=m.Ed;return q};a.MakeWebGLCanvasSurface=function(m,q,x){q=q||null;var y=m,B="undefined"!==
typeof OffscreenCanvas&&y instanceof OffscreenCanvas;if(!("undefined"!==typeof HTMLCanvasElement&&y instanceof HTMLCanvasElement||B||(y=document.getElementById(m),y)))throw"Canvas with id "+m+" was not found";m=this.GetWebGLContext(y,x);if(!m||0>m)throw"failed to create webgl context: err "+m;m=this.MakeWebGLContext(m);q=this.MakeOnScreenGLSurface(m,y.width,y.height,q);return q?q:(q=y.cloneNode(!0),y.parentNode.replaceChild(q,y),q.classList.add("ck-replaced"),a.MakeSWCanvasSurface(q))};a.MakeCanvasSurface=
a.MakeWebGLCanvasSurface;a.Surface.prototype.makeImageFromTexture=function(m,q){a.Fd(this.Ed);m=c(m);if(q=this._makeImageFromTexture(this.Ed,m,q))q.de=m;return q};a.Surface.prototype.makeImageFromTextureSource=function(m,q,x){q||(q={height:e(m),width:f(m),colorType:a.ColorType.RGBA_8888,alphaType:x?a.AlphaType.Premul:a.AlphaType.Unpremul});q.colorSpace||(q.colorSpace=a.ColorSpace.SRGB);a.Fd(this.Ed);var y=w.Qd;x=k(y,y.createTexture(),q,x);2===w.version?y.texImage2D(y.TEXTURE_2D,0,y.RGBA,q.width,q.height,
0,y.RGBA,y.UNSIGNED_BYTE,m):y.texImage2D(y.TEXTURE_2D,0,y.RGBA,y.RGBA,y.UNSIGNED_BYTE,m);l(y,q);this._resetContext();return this.makeImageFromTexture(x,q)};a.Surface.prototype.updateTextureFromSource=function(m,q,x){if(m.de){a.Fd(this.Ed);var y=m.getImageInfo(),B=w.Qd,D=k(B,ea[m.de],y,x);2===w.version?B.texImage2D(B.TEXTURE_2D,0,B.RGBA,f(q),e(q),0,B.RGBA,B.UNSIGNED_BYTE,q):B.texImage2D(B.TEXTURE_2D,0,B.RGBA,B.RGBA,B.UNSIGNED_BYTE,q);l(B,y,x);this._resetContext();ea[m.de]=null;m.de=c(D);y.colorSpace=
m.getColorSpace();q=this._makeImageFromTexture(this.Ed,m.de,y);x=m.jd.Gd;B=m.jd.Ld;m.jd.Gd=q.jd.Gd;m.jd.Ld=q.jd.Ld;q.jd.Gd=x;q.jd.Ld=B;q.delete();y.colorSpace.delete()}};a.MakeLazyImageFromTextureSource=function(m,q,x){q||(q={height:e(m),width:f(m),colorType:a.ColorType.RGBA_8888,alphaType:x?a.AlphaType.Premul:a.AlphaType.Unpremul});q.colorSpace||(q.colorSpace=a.ColorSpace.SRGB);var y={makeTexture:function(){var B=w,D=B.Qd,u=k(D,D.createTexture(),q,x);2===B.version?D.texImage2D(D.TEXTURE_2D,0,D.RGBA,
q.width,q.height,0,D.RGBA,D.UNSIGNED_BYTE,m):D.texImage2D(D.TEXTURE_2D,0,D.RGBA,D.RGBA,D.UNSIGNED_BYTE,m);l(D,q,x);return c(u)},freeSrc:function(){}};"VideoFrame"===m.constructor.name&&(y.freeSrc=function(){m.close()});return a.Image._makeFromGenerator(q,y)};a.Fd=function(m){return m?ha(m):!1};a.je=function(){return w&&w.ve&&!w.ve.isDeleted()?w.ve:null}})})(r);
(function(a){function b(g){return(f(255*g[3])<<24|f(255*g[0])<<16|f(255*g[1])<<8|f(255*g[2])<<0)>>>0}function c(g){if(g&&g._ck)return g;if(g instanceof Float32Array){for(var d=Math.floor(g.length/4),h=new Uint32Array(d),n=0;n<d;n++)h[n]=b(g.slice(4*n,4*(n+1)));return h}if(g instanceof Uint32Array)return g;if(g instanceof Array&&g[0]instanceof Float32Array)return g.map(b)}function e(g){if(void 0===g)return 1;var d=parseFloat(g);return g&&-1!==g.indexOf("%")?d/100:d}function f(g){return Math.round(Math.max(0,
Math.min(g||0,255)))}function k(g,d){d&&d._ck||a._free(g)}function l(g,d,h){if(!g||!g.length)return N;if(g&&g._ck)return g.byteOffset;var n=a[d].BYTES_PER_ELEMENT;h||(h=a._malloc(g.length*n));a[d].set(g,h/n);return h}function m(g){var d={Nd:N,count:g.length,colorType:a.ColorType.RGBA_F32};if(g instanceof Float32Array)d.Nd=l(g,"HEAPF32"),d.count=g.length/4;else if(g instanceof Uint32Array)d.Nd=l(g,"HEAPU32"),d.colorType=a.ColorType.RGBA_8888;else if(g instanceof Array){if(g&&g.length){for(var h=a._malloc(16*
g.length),n=0,t=h/4,v=0;v<g.length;v++)for(var z=0;4>z;z++)a.HEAPF32[t+n]=g[v][z],n++;g=h}else g=N;d.Nd=g}else throw"Invalid argument to copyFlexibleColorArray, Not a color array "+typeof g;return d}function q(g){if(!g)return N;var d=T.toTypedArray();if(g.length){if(6===g.length||9===g.length)return l(g,"HEAPF32",H),6===g.length&&a.HEAPF32.set(ed,6+H/4),H;if(16===g.length)return d[0]=g[0],d[1]=g[1],d[2]=g[3],d[3]=g[4],d[4]=g[5],d[5]=g[7],d[6]=g[12],d[7]=g[13],d[8]=g[15],H;throw"invalid matrix size";
}if(void 0===g.m11)throw"invalid matrix argument";d[0]=g.m11;d[1]=g.m21;d[2]=g.m41;d[3]=g.m12;d[4]=g.m22;d[5]=g.m42;d[6]=g.m14;d[7]=g.m24;d[8]=g.m44;return H}function x(g){if(!g)return N;var d=X.toTypedArray();if(g.length){if(16!==g.length&&6!==g.length&&9!==g.length)throw"invalid matrix size";if(16===g.length)return l(g,"HEAPF32",ba);d.fill(0);d[0]=g[0];d[1]=g[1];d[3]=g[2];d[4]=g[3];d[5]=g[4];d[7]=g[5];d[10]=1;d[12]=g[6];d[13]=g[7];d[15]=g[8];6===g.length&&(d[12]=0,d[13]=0,d[15]=1);return ba}if(void 0===
g.m11)throw"invalid matrix argument";d[0]=g.m11;d[1]=g.m21;d[2]=g.m31;d[3]=g.m41;d[4]=g.m12;d[5]=g.m22;d[6]=g.m32;d[7]=g.m42;d[8]=g.m13;d[9]=g.m23;d[10]=g.m33;d[11]=g.m43;d[12]=g.m14;d[13]=g.m24;d[14]=g.m34;d[15]=g.m44;return ba}function y(g,d){return l(g,"HEAPF32",d||ua)}function B(g,d,h,n){var t=La.toTypedArray();t[0]=g;t[1]=d;t[2]=h;t[3]=n;return ua}function D(g){for(var d=new Float32Array(4),h=0;4>h;h++)d[h]=a.HEAPF32[g/4+h];return d}function u(g,d){return l(g,"HEAPF32",d||W)}function E(g,d){return l(g,
"HEAPF32",d||Db)}a.Color=function(g,d,h,n){void 0===n&&(n=1);return a.Color4f(f(g)/255,f(d)/255,f(h)/255,n)};a.ColorAsInt=function(g,d,h,n){void 0===n&&(n=255);return(f(n)<<24|f(g)<<16|f(d)<<8|f(h)<<0&268435455)>>>0};a.Color4f=function(g,d,h,n){void 0===n&&(n=1);return Float32Array.of(g,d,h,n)};Object.defineProperty(a,"TRANSPARENT",{get:function(){return a.Color4f(0,0,0,0)}});Object.defineProperty(a,"BLACK",{get:function(){return a.Color4f(0,0,0,1)}});Object.defineProperty(a,"WHITE",{get:function(){return a.Color4f(1,
1,1,1)}});Object.defineProperty(a,"RED",{get:function(){return a.Color4f(1,0,0,1)}});Object.defineProperty(a,"GREEN",{get:function(){return a.Color4f(0,1,0,1)}});Object.defineProperty(a,"BLUE",{get:function(){return a.Color4f(0,0,1,1)}});Object.defineProperty(a,"YELLOW",{get:function(){return a.Color4f(1,1,0,1)}});Object.defineProperty(a,"CYAN",{get:function(){return a.Color4f(0,1,1,1)}});Object.defineProperty(a,"MAGENTA",{get:function(){return a.Color4f(1,0,1,1)}});a.getColorComponents=function(g){return[Math.floor(255*
g[0]),Math.floor(255*g[1]),Math.floor(255*g[2]),g[3]]};a.parseColorString=function(g,d){g=g.toLowerCase();if(g.startsWith("#")){d=255;switch(g.length){case 9:d=parseInt(g.slice(7,9),16);case 7:var h=parseInt(g.slice(1,3),16);var n=parseInt(g.slice(3,5),16);var t=parseInt(g.slice(5,7),16);break;case 5:d=17*parseInt(g.slice(4,5),16);case 4:h=17*parseInt(g.slice(1,2),16),n=17*parseInt(g.slice(2,3),16),t=17*parseInt(g.slice(3,4),16)}return a.Color(h,n,t,d/255)}return g.startsWith("rgba")?(g=g.slice(5,
-1),g=g.split(","),a.Color(+g[0],+g[1],+g[2],e(g[3]))):g.startsWith("rgb")?(g=g.slice(4,-1),g=g.split(","),a.Color(+g[0],+g[1],+g[2],e(g[3]))):g.startsWith("gray(")||g.startsWith("hsl")||!d||(g=d[g],void 0===g)?a.BLACK:g};a.multiplyByAlpha=function(g,d){g=g.slice();g[3]=Math.max(0,Math.min(g[3]*d,1));return g};a.Malloc=function(g,d){var h=a._malloc(d*g.BYTES_PER_ELEMENT);return{_ck:!0,length:d,byteOffset:h,Yd:null,subarray:function(n,t){n=this.toTypedArray().subarray(n,t);n._ck=!0;return n},toTypedArray:function(){if(this.Yd&&
this.Yd.length)return this.Yd;this.Yd=new g(a.HEAPU8.buffer,h,d);this.Yd._ck=!0;return this.Yd}}};a.Free=function(g){a._free(g.byteOffset);g.byteOffset=N;g.toTypedArray=null;g.Yd=null};var H=N,T,ba=N,X,ua=N,La,ma,W=N,ec,Aa=N,fc,Eb=N,gc,Fb=N,gb,Ra=N,hc,Db=N,ic,jc=N,ed=Float32Array.of(0,0,1),N=0;a.onRuntimeInitialized=function(){function g(d,h,n,t,v,z,F){z||(z=4*t.width,t.colorType===a.ColorType.RGBA_F16?z*=2:t.colorType===a.ColorType.RGBA_F32&&(z*=4));var K=z*t.height;var I=v?v.byteOffset:a._malloc(K);
if(F?!d._readPixels(t,I,z,h,n,F):!d._readPixels(t,I,z,h,n))return v||a._free(I),null;if(v)return v.toTypedArray();switch(t.colorType){case a.ColorType.RGBA_8888:case a.ColorType.RGBA_F16:d=(new Uint8Array(a.HEAPU8.buffer,I,K)).slice();break;case a.ColorType.RGBA_F32:d=(new Float32Array(a.HEAPU8.buffer,I,K)).slice();break;default:return null}a._free(I);return d}La=a.Malloc(Float32Array,4);ua=La.byteOffset;X=a.Malloc(Float32Array,16);ba=X.byteOffset;T=a.Malloc(Float32Array,9);H=T.byteOffset;hc=a.Malloc(Float32Array,
12);Db=hc.byteOffset;ic=a.Malloc(Float32Array,12);jc=ic.byteOffset;ma=a.Malloc(Float32Array,4);W=ma.byteOffset;ec=a.Malloc(Float32Array,4);Aa=ec.byteOffset;fc=a.Malloc(Float32Array,3);Eb=fc.byteOffset;gc=a.Malloc(Float32Array,3);Fb=gc.byteOffset;gb=a.Malloc(Int32Array,4);Ra=gb.byteOffset;a.ColorSpace.SRGB=a.ColorSpace._MakeSRGB();a.ColorSpace.DISPLAY_P3=a.ColorSpace._MakeDisplayP3();a.ColorSpace.ADOBE_RGB=a.ColorSpace._MakeAdobeRGB();a.GlyphRunFlags={IsWhiteSpace:a._GlyphRunFlags_isWhiteSpace};a.Path.MakeFromCmds=
function(d){var h=l(d,"HEAPF32"),n=a.Path._MakeFromCmds(h,d.length);k(h,d);return n};a.Path.MakeFromVerbsPointsWeights=function(d,h,n){var t=l(d,"HEAPU8"),v=l(h,"HEAPF32"),z=l(n,"HEAPF32"),F=a.Path._MakeFromVerbsPointsWeights(t,d.length,v,h.length,z,n&&n.length||0);k(t,d);k(v,h);k(z,n);return F};a.Path.prototype.addArc=function(d,h,n){d=u(d);this._addArc(d,h,n);return this};a.Path.prototype.addCircle=function(d,h,n,t){this._addCircle(d,h,n,!!t);return this};a.Path.prototype.addOval=function(d,h,n){void 0===
n&&(n=1);d=u(d);this._addOval(d,!!h,n);return this};a.Path.prototype.addPath=function(){var d=Array.prototype.slice.call(arguments),h=d[0],n=!1;"boolean"===typeof d[d.length-1]&&(n=d.pop());if(1===d.length)this._addPath(h,1,0,0,0,1,0,0,0,1,n);else if(2===d.length)d=d[1],this._addPath(h,d[0],d[1],d[2],d[3],d[4],d[5],d[6]||0,d[7]||0,d[8]||1,n);else if(7===d.length||10===d.length)this._addPath(h,d[1],d[2],d[3],d[4],d[5],d[6],d[7]||0,d[8]||0,d[9]||1,n);else return null;return this};a.Path.prototype.addPoly=
function(d,h){var n=l(d,"HEAPF32");this._addPoly(n,d.length/2,h);k(n,d);return this};a.Path.prototype.addRect=function(d,h){d=u(d);this._addRect(d,!!h);return this};a.Path.prototype.addRRect=function(d,h){d=E(d);this._addRRect(d,!!h);return this};a.Path.prototype.addVerbsPointsWeights=function(d,h,n){var t=l(d,"HEAPU8"),v=l(h,"HEAPF32"),z=l(n,"HEAPF32");this._addVerbsPointsWeights(t,d.length,v,h.length,z,n&&n.length||0);k(t,d);k(v,h);k(z,n)};a.Path.prototype.arc=function(d,h,n,t,v,z){d=a.LTRBRect(d-
n,h-n,d+n,h+n);v=(v-t)/Math.PI*180-360*!!z;z=new a.Path;z.addArc(d,t/Math.PI*180,v);this.addPath(z,!0);z.delete();return this};a.Path.prototype.arcToOval=function(d,h,n,t){d=u(d);this._arcToOval(d,h,n,t);return this};a.Path.prototype.arcToRotated=function(d,h,n,t,v,z,F){this._arcToRotated(d,h,n,!!t,!!v,z,F);return this};a.Path.prototype.arcToTangent=function(d,h,n,t,v){this._arcToTangent(d,h,n,t,v);return this};a.Path.prototype.close=function(){this._close();return this};a.Path.prototype.conicTo=
function(d,h,n,t,v){this._conicTo(d,h,n,t,v);return this};a.Path.prototype.computeTightBounds=function(d){this._computeTightBounds(W);var h=ma.toTypedArray();return d?(d.set(h),d):h.slice()};a.Path.prototype.cubicTo=function(d,h,n,t,v,z){this._cubicTo(d,h,n,t,v,z);return this};a.Path.prototype.dash=function(d,h,n){return this._dash(d,h,n)?this:null};a.Path.prototype.getBounds=function(d){this._getBounds(W);var h=ma.toTypedArray();return d?(d.set(h),d):h.slice()};a.Path.prototype.lineTo=function(d,
h){this._lineTo(d,h);return this};a.Path.prototype.moveTo=function(d,h){this._moveTo(d,h);return this};a.Path.prototype.offset=function(d,h){this._transform(1,0,d,0,1,h,0,0,1);return this};a.Path.prototype.quadTo=function(d,h,n,t){this._quadTo(d,h,n,t);return this};a.Path.prototype.rArcTo=function(d,h,n,t,v,z,F){this._rArcTo(d,h,n,t,v,z,F);return this};a.Path.prototype.rConicTo=function(d,h,n,t,v){this._rConicTo(d,h,n,t,v);return this};a.Path.prototype.rCubicTo=function(d,h,n,t,v,z){this._rCubicTo(d,
h,n,t,v,z);return this};a.Path.prototype.rLineTo=function(d,h){this._rLineTo(d,h);return this};a.Path.prototype.rMoveTo=function(d,h){this._rMoveTo(d,h);return this};a.Path.prototype.rQuadTo=function(d,h,n,t){this._rQuadTo(d,h,n,t);return this};a.Path.prototype.stroke=function(d){d=d||{};d.width=d.width||1;d.miter_limit=d.miter_limit||4;d.cap=d.cap||a.StrokeCap.Butt;d.join=d.join||a.StrokeJoin.Miter;d.precision=d.precision||1;return this._stroke(d)?this:null};a.Path.prototype.transform=function(){if(1===
arguments.length){var d=arguments[0];this._transform(d[0],d[1],d[2],d[3],d[4],d[5],d[6]||0,d[7]||0,d[8]||1)}else if(6===arguments.length||9===arguments.length)d=arguments,this._transform(d[0],d[1],d[2],d[3],d[4],d[5],d[6]||0,d[7]||0,d[8]||1);else throw"transform expected to take 1 or 9 arguments. Got "+arguments.length;return this};a.Path.prototype.trim=function(d,h,n){return this._trim(d,h,!!n)?this:null};a.Image.prototype.encodeToBytes=function(d,h){var n=a.je();d=d||a.ImageFormat.PNG;h=h||100;
return n?this._encodeToBytes(d,h,n):this._encodeToBytes(d,h)};a.Image.prototype.makeShaderCubic=function(d,h,n,t,v){v=q(v);return this._makeShaderCubic(d,h,n,t,v)};a.Image.prototype.makeShaderOptions=function(d,h,n,t,v){v=q(v);return this._makeShaderOptions(d,h,n,t,v)};a.Image.prototype.readPixels=function(d,h,n,t,v){var z=a.je();return g(this,d,h,n,t,v,z)};a.Canvas.prototype.clear=function(d){a.Fd(this.Ed);d=y(d);this._clear(d)};a.Canvas.prototype.clipRRect=function(d,h,n){a.Fd(this.Ed);d=E(d);this._clipRRect(d,
h,n)};a.Canvas.prototype.clipRect=function(d,h,n){a.Fd(this.Ed);d=u(d);this._clipRect(d,h,n)};a.Canvas.prototype.concat=function(d){a.Fd(this.Ed);d=x(d);this._concat(d)};a.Canvas.prototype.drawArc=function(d,h,n,t,v){a.Fd(this.Ed);d=u(d);this._drawArc(d,h,n,t,v)};a.Canvas.prototype.drawAtlas=function(d,h,n,t,v,z,F){if(d&&t&&h&&n&&h.length===n.length){a.Fd(this.Ed);v||(v=a.BlendMode.SrcOver);var K=l(h,"HEAPF32"),I=l(n,"HEAPF32"),U=n.length/4,p=l(c(z),"HEAPU32");if(F&&"B"in F&&"C"in F)this._drawAtlasCubic(d,
I,K,p,U,v,F.B,F.C,t);else{let A=a.FilterMode.Linear,M=a.MipmapMode.None;F&&(A=F.filter,"mipmap"in F&&(M=F.mipmap));this._drawAtlasOptions(d,I,K,p,U,v,A,M,t)}k(K,h);k(I,n);k(p,z)}};a.Canvas.prototype.drawCircle=function(d,h,n,t){a.Fd(this.Ed);this._drawCircle(d,h,n,t)};a.Canvas.prototype.drawColor=function(d,h){a.Fd(this.Ed);d=y(d);void 0!==h?this._drawColor(d,h):this._drawColor(d)};a.Canvas.prototype.drawColorInt=function(d,h){a.Fd(this.Ed);this._drawColorInt(d,h||a.BlendMode.SrcOver)};a.Canvas.prototype.drawColorComponents=
function(d,h,n,t,v){a.Fd(this.Ed);d=B(d,h,n,t);void 0!==v?this._drawColor(d,v):this._drawColor(d)};a.Canvas.prototype.drawDRRect=function(d,h,n){a.Fd(this.Ed);d=E(d,Db);h=E(h,jc);this._drawDRRect(d,h,n)};a.Canvas.prototype.drawImage=function(d,h,n,t){a.Fd(this.Ed);this._drawImage(d,h,n,t||null)};a.Canvas.prototype.drawImageCubic=function(d,h,n,t,v,z){a.Fd(this.Ed);this._drawImageCubic(d,h,n,t,v,z||null)};a.Canvas.prototype.drawImageOptions=function(d,h,n,t,v,z){a.Fd(this.Ed);this._drawImageOptions(d,
h,n,t,v,z||null)};a.Canvas.prototype.drawImageNine=function(d,h,n,t,v){a.Fd(this.Ed);h=l(h,"HEAP32",Ra);n=u(n);this._drawImageNine(d,h,n,t,v||null)};a.Canvas.prototype.drawImageRect=function(d,h,n,t,v){a.Fd(this.Ed);u(h,W);u(n,Aa);this._drawImageRect(d,W,Aa,t,!!v)};a.Canvas.prototype.drawImageRectCubic=function(d,h,n,t,v,z){a.Fd(this.Ed);u(h,W);u(n,Aa);this._drawImageRectCubic(d,W,Aa,t,v,z||null)};a.Canvas.prototype.drawImageRectOptions=function(d,h,n,t,v,z){a.Fd(this.Ed);u(h,W);u(n,Aa);this._drawImageRectOptions(d,
W,Aa,t,v,z||null)};a.Canvas.prototype.drawLine=function(d,h,n,t,v){a.Fd(this.Ed);this._drawLine(d,h,n,t,v)};a.Canvas.prototype.drawOval=function(d,h){a.Fd(this.Ed);d=u(d);this._drawOval(d,h)};a.Canvas.prototype.drawPaint=function(d){a.Fd(this.Ed);this._drawPaint(d)};a.Canvas.prototype.drawParagraph=function(d,h,n){a.Fd(this.Ed);this._drawParagraph(d,h,n)};a.Canvas.prototype.drawPatch=function(d,h,n,t,v){if(24>d.length)throw"Need 12 cubic points";if(h&&4>h.length)throw"Need 4 colors";if(n&&8>n.length)throw"Need 4 shader coordinates";
a.Fd(this.Ed);const z=l(d,"HEAPF32"),F=h?l(c(h),"HEAPU32"):N,K=n?l(n,"HEAPF32"):N;t||(t=a.BlendMode.Modulate);this._drawPatch(z,F,K,t,v);k(K,n);k(F,h);k(z,d)};a.Canvas.prototype.drawPath=function(d,h){a.Fd(this.Ed);this._drawPath(d,h)};a.Canvas.prototype.drawPicture=function(d){a.Fd(this.Ed);this._drawPicture(d)};a.Canvas.prototype.drawPoints=function(d,h,n){a.Fd(this.Ed);var t=l(h,"HEAPF32");this._drawPoints(d,t,h.length/2,n);k(t,h)};a.Canvas.prototype.drawRRect=function(d,h){a.Fd(this.Ed);d=E(d);
this._drawRRect(d,h)};a.Canvas.prototype.drawRect=function(d,h){a.Fd(this.Ed);d=u(d);this._drawRect(d,h)};a.Canvas.prototype.drawRect4f=function(d,h,n,t,v){a.Fd(this.Ed);this._drawRect4f(d,h,n,t,v)};a.Canvas.prototype.drawShadow=function(d,h,n,t,v,z,F){a.Fd(this.Ed);var K=l(v,"HEAPF32"),I=l(z,"HEAPF32");h=l(h,"HEAPF32",Eb);n=l(n,"HEAPF32",Fb);this._drawShadow(d,h,n,t,K,I,F);k(K,v);k(I,z)};a.getShadowLocalBounds=function(d,h,n,t,v,z,F){d=q(d);n=l(n,"HEAPF32",Eb);t=l(t,"HEAPF32",Fb);if(!this._getShadowLocalBounds(d,
h,n,t,v,z,W))return null;h=ma.toTypedArray();return F?(F.set(h),F):h.slice()};a.Canvas.prototype.drawTextBlob=function(d,h,n,t){a.Fd(this.Ed);this._drawTextBlob(d,h,n,t)};a.Canvas.prototype.drawVertices=function(d,h,n){a.Fd(this.Ed);this._drawVertices(d,h,n)};a.Canvas.prototype.getDeviceClipBounds=function(d){this._getDeviceClipBounds(Ra);var h=gb.toTypedArray();d?d.set(h):d=h.slice();return d};a.Canvas.prototype.getLocalToDevice=function(){this._getLocalToDevice(ba);for(var d=ba,h=Array(16),n=0;16>
n;n++)h[n]=a.HEAPF32[d/4+n];return h};a.Canvas.prototype.getTotalMatrix=function(){this._getTotalMatrix(H);for(var d=Array(9),h=0;9>h;h++)d[h]=a.HEAPF32[H/4+h];return d};a.Canvas.prototype.makeSurface=function(d){d=this._makeSurface(d);d.Ed=this.Ed;return d};a.Canvas.prototype.readPixels=function(d,h,n,t,v){a.Fd(this.Ed);return g(this,d,h,n,t,v)};a.Canvas.prototype.saveLayer=function(d,h,n,t){h=u(h);return this._saveLayer(d||null,h,n||null,t||0)};a.Canvas.prototype.writePixels=function(d,h,n,t,v,
z,F,K){if(d.byteLength%(h*n))throw"pixels length must be a multiple of the srcWidth * srcHeight";a.Fd(this.Ed);var I=d.byteLength/(h*n);z=z||a.AlphaType.Unpremul;F=F||a.ColorType.RGBA_8888;K=K||a.ColorSpace.SRGB;var U=I*h;I=l(d,"HEAPU8");h=this._writePixels({width:h,height:n,colorType:F,alphaType:z,colorSpace:K},I,U,t,v);k(I,d);return h};a.ColorFilter.MakeBlend=function(d,h,n){d=y(d);n=n||a.ColorSpace.SRGB;return a.ColorFilter._MakeBlend(d,h,n)};a.ColorFilter.MakeMatrix=function(d){if(!d||20!==d.length)throw"invalid color matrix";
var h=l(d,"HEAPF32"),n=a.ColorFilter._makeMatrix(h);k(h,d);return n};a.ContourMeasure.prototype.getPosTan=function(d,h){this._getPosTan(d,W);d=ma.toTypedArray();return h?(h.set(d),h):d.slice()};a.ImageFilter.prototype.getOutputBounds=function(d,h,n){d=u(d,W);h=q(h);this._getOutputBounds(d,h,Ra);h=gb.toTypedArray();return n?(n.set(h),n):h.slice()};a.ImageFilter.MakeDropShadow=function(d,h,n,t,v,z){v=y(v,ua);return a.ImageFilter._MakeDropShadow(d,h,n,t,v,z)};a.ImageFilter.MakeDropShadowOnly=function(d,
h,n,t,v,z){v=y(v,ua);return a.ImageFilter._MakeDropShadowOnly(d,h,n,t,v,z)};a.ImageFilter.MakeImage=function(d,h,n,t){n=u(n,W);t=u(t,Aa);if("B"in h&&"C"in h)return a.ImageFilter._MakeImageCubic(d,h.B,h.C,n,t);const v=h.filter;let z=a.MipmapMode.None;"mipmap"in h&&(z=h.mipmap);return a.ImageFilter._MakeImageOptions(d,v,z,n,t)};a.ImageFilter.MakeMatrixTransform=function(d,h,n){d=q(d);if("B"in h&&"C"in h)return a.ImageFilter._MakeMatrixTransformCubic(d,h.B,h.C,n);const t=h.filter;let v=a.MipmapMode.None;
"mipmap"in h&&(v=h.mipmap);return a.ImageFilter._MakeMatrixTransformOptions(d,t,v,n)};a.Paint.prototype.getColor=function(){this._getColor(ua);return D(ua)};a.Paint.prototype.setColor=function(d,h){h=h||null;d=y(d);this._setColor(d,h)};a.Paint.prototype.setColorComponents=function(d,h,n,t,v){v=v||null;d=B(d,h,n,t);this._setColor(d,v)};a.Path.prototype.getPoint=function(d,h){this._getPoint(d,W);d=ma.toTypedArray();return h?(h[0]=d[0],h[1]=d[1],h):d.slice(0,2)};a.Picture.prototype.makeShader=function(d,
h,n,t,v){t=q(t);v=u(v);return this._makeShader(d,h,n,t,v)};a.Picture.prototype.cullRect=function(d){this._cullRect(W);var h=ma.toTypedArray();return d?(d.set(h),d):h.slice()};a.PictureRecorder.prototype.beginRecording=function(d,h){d=u(d);return this._beginRecording(d,!!h)};a.Surface.prototype.getCanvas=function(){var d=this._getCanvas();d.Ed=this.Ed;return d};a.Surface.prototype.makeImageSnapshot=function(d){a.Fd(this.Ed);d=l(d,"HEAP32",Ra);return this._makeImageSnapshot(d)};a.Surface.prototype.makeSurface=
function(d){a.Fd(this.Ed);d=this._makeSurface(d);d.Ed=this.Ed;return d};a.Surface.prototype.Pe=function(d,h){this.ce||(this.ce=this.getCanvas());return requestAnimationFrame(function(){a.Fd(this.Ed);d(this.ce);this.flush(h)}.bind(this))};a.Surface.prototype.requestAnimationFrame||(a.Surface.prototype.requestAnimationFrame=a.Surface.prototype.Pe);a.Surface.prototype.Me=function(d,h){this.ce||(this.ce=this.getCanvas());requestAnimationFrame(function(){a.Fd(this.Ed);d(this.ce);this.flush(h);this.dispose()}.bind(this))};
a.Surface.prototype.drawOnce||(a.Surface.prototype.drawOnce=a.Surface.prototype.Me);a.PathEffect.MakeDash=function(d,h){h||(h=0);if(!d.length||1===d.length%2)throw"Intervals array must have even length";var n=l(d,"HEAPF32");h=a.PathEffect._MakeDash(n,d.length,h);k(n,d);return h};a.PathEffect.MakeLine2D=function(d,h){h=q(h);return a.PathEffect._MakeLine2D(d,h)};a.PathEffect.MakePath2D=function(d,h){d=q(d);return a.PathEffect._MakePath2D(d,h)};a.Shader.MakeColor=function(d,h){h=h||null;d=y(d);return a.Shader._MakeColor(d,
h)};a.Shader.Blend=a.Shader.MakeBlend;a.Shader.Color=a.Shader.MakeColor;a.Shader.MakeLinearGradient=function(d,h,n,t,v,z,F,K){K=K||null;var I=m(n),U=l(t,"HEAPF32");F=F||0;z=q(z);var p=ma.toTypedArray();p.set(d);p.set(h,2);d=a.Shader._MakeLinearGradient(W,I.Nd,I.colorType,U,I.count,v,F,z,K);k(I.Nd,n);t&&k(U,t);return d};a.Shader.MakeRadialGradient=function(d,h,n,t,v,z,F,K){K=K||null;var I=m(n),U=l(t,"HEAPF32");F=F||0;z=q(z);d=a.Shader._MakeRadialGradient(d[0],d[1],h,I.Nd,I.colorType,U,I.count,v,F,
z,K);k(I.Nd,n);t&&k(U,t);return d};a.Shader.MakeSweepGradient=function(d,h,n,t,v,z,F,K,I,U){U=U||null;var p=m(n),A=l(t,"HEAPF32");F=F||0;K=K||0;I=I||360;z=q(z);d=a.Shader._MakeSweepGradient(d,h,p.Nd,p.colorType,A,p.count,v,K,I,F,z,U);k(p.Nd,n);t&&k(A,t);return d};a.Shader.MakeTwoPointConicalGradient=function(d,h,n,t,v,z,F,K,I,U){U=U||null;var p=m(v),A=l(z,"HEAPF32");I=I||0;K=q(K);var M=ma.toTypedArray();M.set(d);M.set(n,2);d=a.Shader._MakeTwoPointConicalGradient(W,h,t,p.Nd,p.colorType,A,p.count,F,
I,K,U);k(p.Nd,v);z&&k(A,z);return d};a.Vertices.prototype.bounds=function(d){this._bounds(W);var h=ma.toTypedArray();return d?(d.set(h),d):h.slice()};a.Id&&a.Id.forEach(function(d){d()})};a.computeTonalColors=function(g){var d=l(g.ambient,"HEAPF32"),h=l(g.spot,"HEAPF32");this._computeTonalColors(d,h);var n={ambient:D(d),spot:D(h)};k(d,g.ambient);k(h,g.spot);return n};a.LTRBRect=function(g,d,h,n){return Float32Array.of(g,d,h,n)};a.XYWHRect=function(g,d,h,n){return Float32Array.of(g,d,g+h,d+n)};a.LTRBiRect=
function(g,d,h,n){return Int32Array.of(g,d,h,n)};a.XYWHiRect=function(g,d,h,n){return Int32Array.of(g,d,g+h,d+n)};a.RRectXY=function(g,d,h){return Float32Array.of(g[0],g[1],g[2],g[3],d,h,d,h,d,h,d,h)};a.MakeAnimatedImageFromEncoded=function(g){g=new Uint8Array(g);var d=a._malloc(g.byteLength);a.HEAPU8.set(g,d);return(g=a._decodeAnimatedImage(d,g.byteLength))?g:null};a.MakeImageFromEncoded=function(g){g=new Uint8Array(g);var d=a._malloc(g.byteLength);a.HEAPU8.set(g,d);return(g=a._decodeImage(d,g.byteLength))?
g:null};var Sa=null;a.MakeImageFromCanvasImageSource=function(g){var d=g.width,h=g.height;Sa||(Sa=document.createElement("canvas"));Sa.width=d;Sa.height=h;var n=Sa.getContext("2d",{willReadFrequently:!0});n.drawImage(g,0,0);g=n.getImageData(0,0,d,h);return a.MakeImage({width:d,height:h,alphaType:a.AlphaType.Unpremul,colorType:a.ColorType.RGBA_8888,colorSpace:a.ColorSpace.SRGB},g.data,4*d)};a.MakeImage=function(g,d,h){var n=a._malloc(d.length);a.HEAPU8.set(d,n);return a._MakeImage(g,n,d.length,h)};
a.MakeVertices=function(g,d,h,n,t,v){var z=t&&t.length||0,F=0;h&&h.length&&(F|=1);n&&n.length&&(F|=2);void 0===v||v||(F|=4);g=new a._VerticesBuilder(g,d.length/2,z,F);l(d,"HEAPF32",g.positions());g.texCoords()&&l(h,"HEAPF32",g.texCoords());g.colors()&&l(c(n),"HEAPU32",g.colors());g.indices()&&l(t,"HEAPU16",g.indices());return g.detach()};(function(g){g.Id=g.Id||[];g.Id.push(function(){function d(p){if(!p||!p.length)return[];for(var A=[],M=0;M<p.length;M+=5){var Y=g.LTRBRect(p[M],p[M+1],p[M+2],p[M+
3]),ya=g.TextDirection.LTR;0===p[M+4]&&(ya=g.TextDirection.RTL);A.push({rect:Y,dir:ya})}g._free(p.byteOffset);return A}function h(p){p=p||{};void 0===p.weight&&(p.weight=g.FontWeight.Normal);p.width=p.width||g.FontWidth.Normal;p.slant=p.slant||g.FontSlant.Upright;return p}function n(p){if(!p||!p.length)return N;for(var A=[],M=0;M<p.length;M++){var Y=t(p[M]);A.push(Y)}return l(A,"HEAPU32")}function t(p){if(F[p])return F[p];var A=ja(p)+1,M=g._malloc(A);ka(p,C,M,A);return F[p]=M}function v(p){p._colorPtr=
y(p.color);p._foregroundColorPtr=N;p._backgroundColorPtr=N;p._decorationColorPtr=N;p.foregroundColor&&(p._foregroundColorPtr=y(p.foregroundColor,K));p.backgroundColor&&(p._backgroundColorPtr=y(p.backgroundColor,I));p.decorationColor&&(p._decorationColorPtr=y(p.decorationColor,U));Array.isArray(p.fontFamilies)&&p.fontFamilies.length?(p._fontFamiliesPtr=n(p.fontFamilies),p._fontFamiliesLen=p.fontFamilies.length):(p._fontFamiliesPtr=N,p._fontFamiliesLen=0);if(p.locale){var A=p.locale;p._localePtr=t(A);
p._localeLen=ja(A)+1}else p._localePtr=N,p._localeLen=0;if(Array.isArray(p.shadows)&&p.shadows.length){A=p.shadows;var M=A.map(function(pa){return pa.color||g.BLACK}),Y=A.map(function(pa){return pa.blurRadius||0});p._shadowLen=A.length;for(var ya=g._malloc(8*A.length),Gb=ya/4,Hb=0;Hb<A.length;Hb++){var kc=A[Hb].offset||[0,0];g.HEAPF32[Gb]=kc[0];g.HEAPF32[Gb+1]=kc[1];Gb+=2}p._shadowColorsPtr=m(M).Nd;p._shadowOffsetsPtr=ya;p._shadowBlurRadiiPtr=l(Y,"HEAPF32")}else p._shadowLen=0,p._shadowColorsPtr=
N,p._shadowOffsetsPtr=N,p._shadowBlurRadiiPtr=N;Array.isArray(p.fontFeatures)&&p.fontFeatures.length?(A=p.fontFeatures,M=A.map(function(pa){return pa.name}),Y=A.map(function(pa){return pa.value}),p._fontFeatureLen=A.length,p._fontFeatureNamesPtr=n(M),p._fontFeatureValuesPtr=l(Y,"HEAPU32")):(p._fontFeatureLen=0,p._fontFeatureNamesPtr=N,p._fontFeatureValuesPtr=N);Array.isArray(p.fontVariations)&&p.fontVariations.length?(A=p.fontVariations,M=A.map(function(pa){return pa.axis}),Y=A.map(function(pa){return pa.value}),
p._fontVariationLen=A.length,p._fontVariationAxesPtr=n(M),p._fontVariationValuesPtr=l(Y,"HEAPF32")):(p._fontVariationLen=0,p._fontVariationAxesPtr=N,p._fontVariationValuesPtr=N)}function z(p){g._free(p._fontFamiliesPtr);g._free(p._shadowColorsPtr);g._free(p._shadowOffsetsPtr);g._free(p._shadowBlurRadiiPtr);g._free(p._fontFeatureNamesPtr);g._free(p._fontFeatureValuesPtr);g._free(p._fontVariationAxesPtr);g._free(p._fontVariationValuesPtr)}g.Paragraph.prototype.getRectsForRange=function(p,A,M,Y){p=this._getRectsForRange(p,
A,M,Y);return d(p)};g.Paragraph.prototype.getRectsForPlaceholders=function(){var p=this._getRectsForPlaceholders();return d(p)};g.TypefaceFontProvider.prototype.registerFont=function(p,A){p=g.Typeface.MakeFreeTypeFaceFromData(p);if(!p)return null;A=t(A);this._registerFont(p,A)};g.ParagraphStyle=function(p){p.disableHinting=p.disableHinting||!1;if(p.ellipsis){var A=p.ellipsis;p._ellipsisPtr=t(A);p._ellipsisLen=ja(A)+1}else p._ellipsisPtr=N,p._ellipsisLen=0;null==p.heightMultiplier&&(p.heightMultiplier=
-1);p.maxLines=p.maxLines||0;p.replaceTabCharacters=p.replaceTabCharacters||!1;A=(A=p.strutStyle)||{};A.strutEnabled=A.strutEnabled||!1;A.strutEnabled&&Array.isArray(A.fontFamilies)&&A.fontFamilies.length?(A._fontFamiliesPtr=n(A.fontFamilies),A._fontFamiliesLen=A.fontFamilies.length):(A._fontFamiliesPtr=N,A._fontFamiliesLen=0);A.fontStyle=h(A.fontStyle);null==A.fontSize&&(A.fontSize=-1);null==A.heightMultiplier&&(A.heightMultiplier=-1);A.halfLeading=A.halfLeading||!1;A.leading=A.leading||0;A.forceStrutHeight=
A.forceStrutHeight||!1;p.strutStyle=A;p.textAlign=p.textAlign||g.TextAlign.Start;p.textDirection=p.textDirection||g.TextDirection.LTR;p.textHeightBehavior=p.textHeightBehavior||g.TextHeightBehavior.All;p.textStyle=g.TextStyle(p.textStyle);p.applyRoundingHack=!1!==p.applyRoundingHack;return p};g.TextStyle=function(p){p.color||(p.color=g.BLACK);p.decoration=p.decoration||0;p.decorationThickness=p.decorationThickness||0;p.decorationStyle=p.decorationStyle||g.DecorationStyle.Solid;p.textBaseline=p.textBaseline||
g.TextBaseline.Alphabetic;null==p.fontSize&&(p.fontSize=-1);p.letterSpacing=p.letterSpacing||0;p.wordSpacing=p.wordSpacing||0;null==p.heightMultiplier&&(p.heightMultiplier=-1);p.halfLeading=p.halfLeading||!1;p.fontStyle=h(p.fontStyle);return p};var F={},K=g._malloc(16),I=g._malloc(16),U=g._malloc(16);g.ParagraphBuilder.Make=function(p,A){v(p.textStyle);A=g.ParagraphBuilder._Make(p,A);z(p.textStyle);return A};g.ParagraphBuilder.MakeFromFontProvider=function(p,A){v(p.textStyle);A=g.ParagraphBuilder._MakeFromFontProvider(p,
A);z(p.textStyle);return A};g.ParagraphBuilder.MakeFromFontCollection=function(p,A){v(p.textStyle);A=g.ParagraphBuilder._MakeFromFontCollection(p,A);z(p.textStyle);return A};g.ParagraphBuilder.ShapeText=function(p,A,M){let Y=0;for(const ya of A)Y+=ya.length;if(Y!==p.length)throw"Accumulated block lengths must equal text.length";return g.ParagraphBuilder._ShapeText(p,A,M)};g.ParagraphBuilder.prototype.pushStyle=function(p){v(p);this._pushStyle(p);z(p)};g.ParagraphBuilder.prototype.pushPaintStyle=function(p,
A,M){v(p);this._pushPaintStyle(p,A,M);z(p)};g.ParagraphBuilder.prototype.addPlaceholder=function(p,A,M,Y,ya){M=M||g.PlaceholderAlignment.Baseline;Y=Y||g.TextBaseline.Alphabetic;this._addPlaceholder(p||0,A||0,M,Y,ya||0)};g.ParagraphBuilder.prototype.setWordsUtf8=function(p){var A=l(p,"HEAPU32");this._setWordsUtf8(A,p&&p.length||0);k(A,p)};g.ParagraphBuilder.prototype.setWordsUtf16=function(p){var A=l(p,"HEAPU32");this._setWordsUtf16(A,p&&p.length||0);k(A,p)};g.ParagraphBuilder.prototype.setGraphemeBreaksUtf8=
function(p){var A=l(p,"HEAPU32");this._setGraphemeBreaksUtf8(A,p&&p.length||0);k(A,p)};g.ParagraphBuilder.prototype.setGraphemeBreaksUtf16=function(p){var A=l(p,"HEAPU32");this._setGraphemeBreaksUtf16(A,p&&p.length||0);k(A,p)};g.ParagraphBuilder.prototype.setLineBreaksUtf8=function(p){var A=l(p,"HEAPU32");this._setLineBreaksUtf8(A,p&&p.length||0);k(A,p)};g.ParagraphBuilder.prototype.setLineBreaksUtf16=function(p){var A=l(p,"HEAPU32");this._setLineBreaksUtf16(A,p&&p.length||0);k(A,p)}})})(r);a.Id=
a.Id||[];a.Id.push(function(){a.Path.prototype.op=function(g,d){return this._op(g,d)?this:null};a.Path.prototype.simplify=function(){return this._simplify()?this:null}});a.Id=a.Id||[];a.Id.push(function(){a.Canvas.prototype.drawText=function(g,d,h,n,t){var v=ja(g),z=a._malloc(v+1);ka(g,C,z,v+1);this._drawSimpleText(z,v,d,h,t,n);a._free(z)};a.Canvas.prototype.drawGlyphs=function(g,d,h,n,t,v){if(!(2*g.length<=d.length))throw"Not enough positions for the array of gyphs";a.Fd(this.Ed);const z=l(g,"HEAPU16"),
F=l(d,"HEAPF32");this._drawGlyphs(g.length,z,F,h,n,t,v);k(F,d);k(z,g)};a.Font.prototype.getGlyphBounds=function(g,d,h){var n=l(g,"HEAPU16"),t=a._malloc(16*g.length);this._getGlyphWidthBounds(n,g.length,N,t,d||null);d=new Float32Array(a.HEAPU8.buffer,t,4*g.length);k(n,g);if(h)return h.set(d),a._free(t),h;g=Float32Array.from(d);a._free(t);return g};a.Font.prototype.getGlyphIDs=function(g,d,h){d||(d=g.length);var n=ja(g)+1,t=a._malloc(n);ka(g,C,t,n);g=a._malloc(2*d);d=this._getGlyphIDs(t,n-1,d,g);a._free(t);
if(0>d)return a._free(g),null;t=new Uint16Array(a.HEAPU8.buffer,g,d);if(h)return h.set(t),a._free(g),h;h=Uint16Array.from(t);a._free(g);return h};a.Font.prototype.getGlyphIntercepts=function(g,d,h,n){var t=l(g,"HEAPU16"),v=l(d,"HEAPF32");return this._getGlyphIntercepts(t,g.length,!(g&&g._ck),v,d.length,!(d&&d._ck),h,n)};a.Font.prototype.getGlyphWidths=function(g,d,h){var n=l(g,"HEAPU16"),t=a._malloc(4*g.length);this._getGlyphWidthBounds(n,g.length,t,N,d||null);d=new Float32Array(a.HEAPU8.buffer,t,
g.length);k(n,g);if(h)return h.set(d),a._free(t),h;g=Float32Array.from(d);a._free(t);return g};a.FontMgr.FromData=function(){if(!arguments.length)return null;var g=arguments;1===g.length&&Array.isArray(g[0])&&(g=arguments[0]);if(!g.length)return null;for(var d=[],h=[],n=0;n<g.length;n++){var t=new Uint8Array(g[n]),v=l(t,"HEAPU8");d.push(v);h.push(t.byteLength)}d=l(d,"HEAPU32");h=l(h,"HEAPU32");g=a.FontMgr._fromData(d,h,g.length);a._free(d);a._free(h);return g};a.Typeface.MakeFreeTypeFaceFromData=
function(g){g=new Uint8Array(g);var d=l(g,"HEAPU8");return(g=a.Typeface._MakeFreeTypeFaceFromData(d,g.byteLength))?g:null};a.Typeface.prototype.getGlyphIDs=function(g,d,h){d||(d=g.length);var n=ja(g)+1,t=a._malloc(n);ka(g,C,t,n);g=a._malloc(2*d);d=this._getGlyphIDs(t,n-1,d,g);a._free(t);if(0>d)return a._free(g),null;t=new Uint16Array(a.HEAPU8.buffer,g,d);if(h)return h.set(t),a._free(g),h;h=Uint16Array.from(t);a._free(g);return h};a.TextBlob.MakeOnPath=function(g,d,h,n){if(g&&g.length&&d&&d.countPoints()){if(1===
d.countPoints())return this.MakeFromText(g,h);n||(n=0);var t=h.getGlyphIDs(g);t=h.getGlyphWidths(t);var v=[];d=new a.ContourMeasureIter(d,!1,1);for(var z=d.next(),F=new Float32Array(4),K=0;K<g.length&&z;K++){var I=t[K];n+=I/2;if(n>z.length()){z.delete();z=d.next();if(!z){g=g.substring(0,K);break}n=I/2}z.getPosTan(n,F);var U=F[2],p=F[3];v.push(U,p,F[0]-I/2*U,F[1]-I/2*p);n+=I/2}g=this.MakeFromRSXform(g,v,h);z&&z.delete();d.delete();return g}};a.TextBlob.MakeFromRSXform=function(g,d,h){var n=ja(g)+1,
t=a._malloc(n);ka(g,C,t,n);g=l(d,"HEAPF32");h=a.TextBlob._MakeFromRSXform(t,n-1,g,h);a._free(t);return h?h:null};a.TextBlob.MakeFromRSXformGlyphs=function(g,d,h){var n=l(g,"HEAPU16");d=l(d,"HEAPF32");h=a.TextBlob._MakeFromRSXformGlyphs(n,2*g.length,d,h);k(n,g);return h?h:null};a.TextBlob.MakeFromGlyphs=function(g,d){var h=l(g,"HEAPU16");d=a.TextBlob._MakeFromGlyphs(h,2*g.length,d);k(h,g);return d?d:null};a.TextBlob.MakeFromText=function(g,d){var h=ja(g)+1,n=a._malloc(h);ka(g,C,n,h);g=a.TextBlob._MakeFromText(n,
h-1,d);a._free(n);return g?g:null};a.MallocGlyphIDs=function(g){return a.Malloc(Uint16Array,g)}});a.Id=a.Id||[];a.Id.push(function(){a.MakePicture=function(g){g=new Uint8Array(g);var d=a._malloc(g.byteLength);a.HEAPU8.set(g,d);return(g=a._MakePicture(d,g.byteLength))?g:null}});a.Id=a.Id||[];a.Id.push(function(){a.RuntimeEffect.Make=function(g,d){return a.RuntimeEffect._Make(g,{onError:d||function(h){console.log("RuntimeEffect error",h)}})};a.RuntimeEffect.MakeForBlender=function(g,d){return a.RuntimeEffect._MakeForBlender(g,
{onError:d||function(h){console.log("RuntimeEffect error",h)}})};a.RuntimeEffect.prototype.makeShader=function(g,d){var h=!g._ck,n=l(g,"HEAPF32");d=q(d);return this._makeShader(n,4*g.length,h,d)};a.RuntimeEffect.prototype.makeShaderWithChildren=function(g,d,h){var n=!g._ck,t=l(g,"HEAPF32");h=q(h);for(var v=[],z=0;z<d.length;z++)v.push(d[z].jd.Gd);d=l(v,"HEAPU32");return this._makeShaderWithChildren(t,4*g.length,n,d,v.length,h)};a.RuntimeEffect.prototype.makeBlender=function(g){var d=!g._ck,h=l(g,
"HEAPF32");return this._makeBlender(h,4*g.length,d)}})})(r);var la=Object.assign({},r),na="./this.program",oa=(a,b)=>{throw b;},qa="object"==typeof window,ra="function"==typeof importScripts,sa="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,ta="",va,wa,xa;
if(sa){var fs=require("fs"),za=require("path");ta=ra?za.dirname(ta)+"/":__dirname+"/";va=(a,b)=>{a=a.startsWith("file://")?new URL(a):za.normalize(a);return fs.readFileSync(a,b?void 0:"utf8")};xa=a=>{a=va(a,!0);a.buffer||(a=new Uint8Array(a));return a};wa=(a,b,c,e=!0)=>{a=a.startsWith("file://")?new URL(a):za.normalize(a);fs.readFile(a,e?void 0:"utf8",(f,k)=>{f?c(f):b(e?k.buffer:k)})};!r.thisProgram&&1<process.argv.length&&(na=process.argv[1].replace(/\\/g,"/"));process.argv.slice(2);oa=(a,b)=>{process.exitCode=
a;throw b;};r.inspect=()=>"[Emscripten Module object]"}else if(qa||ra)ra?ta=self.location.href:"undefined"!=typeof document&&document.currentScript&&(ta=document.currentScript.src),_scriptDir&&(ta=_scriptDir),0!==ta.indexOf("blob:")?ta=ta.substr(0,ta.replace(/[?#].*/,"").lastIndexOf("/")+1):ta="",va=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},ra&&(xa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),
wa=(a,b,c)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?b(e.response):c()};e.onerror=c;e.send(null)};var Ba=r.print||console.log.bind(console),Ca=r.printErr||console.error.bind(console);Object.assign(r,la);la=null;r.thisProgram&&(na=r.thisProgram);r.quit&&(oa=r.quit);var Da;r.wasmBinary&&(Da=r.wasmBinary);var noExitRuntime=r.noExitRuntime||!0;"object"!=typeof WebAssembly&&Ea("no native wasm support detected");
var Fa,G,Ga=!1,Ha,C,Ia,Ja,J,L,O,Ka;function Ma(){var a=Fa.buffer;r.HEAP8=Ha=new Int8Array(a);r.HEAP16=Ia=new Int16Array(a);r.HEAP32=J=new Int32Array(a);r.HEAPU8=C=new Uint8Array(a);r.HEAPU16=Ja=new Uint16Array(a);r.HEAPU32=L=new Uint32Array(a);r.HEAPF32=O=new Float32Array(a);r.HEAPF64=Ka=new Float64Array(a)}var P,Na=[],Oa=[],Pa=[];function Qa(){var a=r.preRun.shift();Na.unshift(a)}var Ta=0,Ua=null,Va=null;
function Ea(a){if(r.onAbort)r.onAbort(a);a="Aborted("+a+")";Ca(a);Ga=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ca(a);throw a;}function Wa(a){return a.startsWith("data:application/octet-stream;base64,")}var Xa;Xa="canvaskit.wasm";if(!Wa(Xa)){var Ya=Xa;Xa=r.locateFile?r.locateFile(Ya,ta):ta+Ya}function Za(a){if(a==Xa&&Da)return new Uint8Array(Da);if(xa)return xa(a);throw"both async and sync fetching of the wasm failed";}
function $a(a){if(!Da&&(qa||ra)){if("function"==typeof fetch&&!a.startsWith("file://"))return fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>Za(a));if(wa)return new Promise((b,c)=>{wa(a,e=>b(new Uint8Array(e)),c)})}return Promise.resolve().then(()=>Za(a))}function ab(a,b,c){return $a(a).then(e=>WebAssembly.instantiate(e,b)).then(e=>e).then(c,e=>{Ca("failed to asynchronously prepare wasm: "+e);Ea(e)})}
function bb(a,b){var c=Xa;return Da||"function"!=typeof WebAssembly.instantiateStreaming||Wa(c)||c.startsWith("file://")||sa||"function"!=typeof fetch?ab(c,a,b):fetch(c,{credentials:"same-origin"}).then(e=>WebAssembly.instantiateStreaming(e,a).then(b,function(f){Ca("wasm streaming compile failed: "+f);Ca("falling back to ArrayBuffer instantiation");return ab(c,a,b)}))}function cb(a){this.name="ExitStatus";this.message=`Program terminated with exit(${a})`;this.status=a}var db=a=>{for(;0<a.length;)a.shift()(r)};
function eb(a){this.Gd=a-24;this.Le=function(b){L[this.Gd+4>>2]=b};this.se=function(b){L[this.Gd+8>>2]=b};this.Vd=function(b,c){this.re();this.Le(b);this.se(c)};this.re=function(){L[this.Gd+16>>2]=0}}
var fb=0,hb=0,ib="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0,jb=(a,b,c)=>{var e=b+c;for(c=b;a[c]&&!(c>=e);)++c;if(16<c-b&&a.buffer&&ib)return ib.decode(a.subarray(b,c));for(e="";b<c;){var f=a[b++];if(f&128){var k=a[b++]&63;if(192==(f&224))e+=String.fromCharCode((f&31)<<6|k);else{var l=a[b++]&63;f=224==(f&240)?(f&15)<<12|k<<6|l:(f&7)<<18|k<<12|l<<6|a[b++]&63;65536>f?e+=String.fromCharCode(f):(f-=65536,e+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else e+=String.fromCharCode(f)}return e},
kb={};function lb(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function mb(a){return this.fromWireType(J[a>>2])}var nb={},ob={},pb={},qb=void 0;function rb(a){throw new qb(a);}
function sb(a,b,c){function e(m){m=c(m);m.length!==a.length&&rb("Mismatched type converter count");for(var q=0;q<a.length;++q)tb(a[q],m[q])}a.forEach(function(m){pb[m]=b});var f=Array(b.length),k=[],l=0;b.forEach((m,q)=>{ob.hasOwnProperty(m)?f[q]=ob[m]:(k.push(m),nb.hasOwnProperty(m)||(nb[m]=[]),nb[m].push(()=>{f[q]=ob[m];++l;l===k.length&&e(f)}))});0===k.length&&e(f)}
function ub(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError(`Unknown type size: ${a}`);}}var vb=void 0;function Q(a){for(var b="";C[a];)b+=vb[C[a++]];return b}var wb=void 0;function R(a){throw new wb(a);}
function xb(a,b,c={}){var e=b.name;a||R(`type "${e}" must have a positive integer typeid pointer`);if(ob.hasOwnProperty(a)){if(c.bf)return;R(`Cannot register type '${e}' twice`)}ob[a]=b;delete pb[a];nb.hasOwnProperty(a)&&(b=nb[a],delete nb[a],b.forEach(f=>f()))}function tb(a,b,c={}){if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");xb(a,b,c)}function yb(a){R(a.jd.Jd.Hd.name+" instance already deleted")}var zb=!1;function Ab(){}
function Bb(a){--a.count.value;0===a.count.value&&(a.Ld?a.Pd.Td(a.Ld):a.Jd.Hd.Td(a.Gd))}function Cb(a,b,c){if(b===c)return a;if(void 0===c.Md)return null;a=Cb(a,b,c.Md);return null===a?null:c.Ue(a)}var Ib={},Jb=[];function Kb(){for(;Jb.length;){var a=Jb.pop();a.jd.ae=!1;a["delete"]()}}var Lb=void 0,Mb={};function Nb(a,b){for(void 0===b&&R("ptr should not be undefined");a.Md;)b=a.ge(b),a=a.Md;return Mb[b]}
function Ob(a,b){b.Jd&&b.Gd||rb("makeClassHandle requires ptr and ptrType");!!b.Pd!==!!b.Ld&&rb("Both smartPtrType and smartPtr must be specified");b.count={value:1};return Pb(Object.create(a,{jd:{value:b}}))}function Pb(a){if("undefined"===typeof FinalizationRegistry)return Pb=b=>b,a;zb=new FinalizationRegistry(b=>{Bb(b.jd)});Pb=b=>{var c=b.jd;c.Ld&&zb.register(b,{jd:c},b);return b};Ab=b=>{zb.unregister(b)};return Pb(a)}function Qb(){}
function Rb(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a}function Sb(a,b){a=Rb(a);return{[a]:function(){return b.apply(this,arguments)}}[a]}
function Tb(a,b,c){if(void 0===a[b].Kd){var e=a[b];a[b]=function(){a[b].Kd.hasOwnProperty(arguments.length)||R(`Function '${c}' called with an invalid number of arguments (${arguments.length}) - expects one of (${a[b].Kd})!`);return a[b].Kd[arguments.length].apply(this,arguments)};a[b].Kd=[];a[b].Kd[e.Zd]=e}}
function Ub(a,b,c){r.hasOwnProperty(a)?((void 0===c||void 0!==r[a].Kd&&void 0!==r[a].Kd[c])&&R(`Cannot register public name '${a}' twice`),Tb(r,a,a),r.hasOwnProperty(c)&&R(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`),r[a].Kd[c]=b):(r[a]=b,void 0!==c&&(r[a].tf=c))}function Vb(a,b,c,e,f,k,l,m){this.name=a;this.constructor=b;this.be=c;this.Td=e;this.Md=f;this.Xe=k;this.ge=l;this.Ue=m;this.ff=[]}
function Wb(a,b,c){for(;b!==c;)b.ge||R(`Expected null or instance of ${c.name}, got an instance of ${b.name}`),a=b.ge(a),b=b.Md;return a}function Xb(a,b){if(null===b)return this.we&&R(`null is not a valid ${this.name}`),0;b.jd||R(`Cannot pass "${Yb(b)}" as a ${this.name}`);b.jd.Gd||R(`Cannot pass deleted object as a pointer of type ${this.name}`);return Wb(b.jd.Gd,b.jd.Jd.Hd,this.Hd)}
function Zb(a,b){if(null===b){this.we&&R(`null is not a valid ${this.name}`);if(this.le){var c=this.xe();null!==a&&a.push(this.Td,c);return c}return 0}b.jd||R(`Cannot pass "${Yb(b)}" as a ${this.name}`);b.jd.Gd||R(`Cannot pass deleted object as a pointer of type ${this.name}`);!this.ke&&b.jd.Jd.ke&&R(`Cannot convert argument of type ${b.jd.Pd?b.jd.Pd.name:b.jd.Jd.name} to parameter type ${this.name}`);c=Wb(b.jd.Gd,b.jd.Jd.Hd,this.Hd);if(this.le)switch(void 0===b.jd.Ld&&R("Passing raw pointer to smart pointer is illegal"),
this.lf){case 0:b.jd.Pd===this?c=b.jd.Ld:R(`Cannot convert argument of type ${b.jd.Pd?b.jd.Pd.name:b.jd.Jd.name} to parameter type ${this.name}`);break;case 1:c=b.jd.Ld;break;case 2:if(b.jd.Pd===this)c=b.jd.Ld;else{var e=b.clone();c=this.gf(c,$b(function(){e["delete"]()}));null!==a&&a.push(this.Td,c)}break;default:R("Unsupporting sharing policy")}return c}
function ac(a,b){if(null===b)return this.we&&R(`null is not a valid ${this.name}`),0;b.jd||R(`Cannot pass "${Yb(b)}" as a ${this.name}`);b.jd.Gd||R(`Cannot pass deleted object as a pointer of type ${this.name}`);b.jd.Jd.ke&&R(`Cannot convert argument of type ${b.jd.Jd.name} to parameter type ${this.name}`);return Wb(b.jd.Gd,b.jd.Jd.Hd,this.Hd)}
function bc(a,b,c,e,f,k,l,m,q,x,y){this.name=a;this.Hd=b;this.we=c;this.ke=e;this.le=f;this.ef=k;this.lf=l;this.Ge=m;this.xe=q;this.gf=x;this.Td=y;f||void 0!==b.Md?this.toWireType=Zb:(this.toWireType=e?Xb:ac,this.Od=null)}function cc(a,b,c){r.hasOwnProperty(a)||rb("Replacing nonexistant public symbol");void 0!==r[a].Kd&&void 0!==c?r[a].Kd[c]=b:(r[a]=b,r[a].Zd=c)}
var dc=(a,b)=>{var c=[];return function(){c.length=0;Object.assign(c,arguments);if(a.includes("j")){var e=r["dynCall_"+a];e=c&&c.length?e.apply(null,[b].concat(c)):e.call(null,b)}else e=P.get(b).apply(null,c);return e}};function lc(a,b){a=Q(a);var c=a.includes("j")?dc(a,b):P.get(b);"function"!=typeof c&&R(`unknown function pointer with signature ${a}: ${b}`);return c}var mc=void 0;function nc(a){a=oc(a);var b=Q(a);pc(a);return b}
function qc(a,b){function c(k){f[k]||ob[k]||(pb[k]?pb[k].forEach(c):(e.push(k),f[k]=!0))}var e=[],f={};b.forEach(c);throw new mc(`${a}: `+e.map(nc).join([", "]));}
function rc(a,b,c,e,f){var k=b.length;2>k&&R("argTypes array size mismatch! Must at least get return value and 'this' types!");var l=null!==b[1]&&null!==c,m=!1;for(c=1;c<b.length;++c)if(null!==b[c]&&void 0===b[c].Od){m=!0;break}var q="void"!==b[0].name,x=k-2,y=Array(x),B=[],D=[];return function(){arguments.length!==x&&R(`function ${a} called with ${arguments.length} arguments, expected ${x} args!`);D.length=0;B.length=l?2:1;B[0]=f;if(l){var u=b[1].toWireType(D,this);B[1]=u}for(var E=0;E<x;++E)y[E]=
b[E+2].toWireType(D,arguments[E]),B.push(y[E]);E=e.apply(null,B);if(m)lb(D);else for(var H=l?1:2;H<b.length;H++){var T=1===H?u:y[H-2];null!==b[H].Od&&b[H].Od(T)}u=q?b[0].fromWireType(E):void 0;return u}}function sc(a,b){for(var c=[],e=0;e<a;e++)c.push(L[b+4*e>>2]);return c}function tc(){this.Sd=[void 0];this.Ee=[]}var uc=new tc;function vc(a){a>=uc.Vd&&0===--uc.get(a).He&&uc.se(a)}
var wc=a=>{a||R("Cannot use deleted val. handle = "+a);return uc.get(a).value},$b=a=>{switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:return uc.re({He:1,value:a})}};function xc(a,b,c){switch(b){case 0:return function(e){return this.fromWireType((c?Ha:C)[e])};case 1:return function(e){return this.fromWireType((c?Ia:Ja)[e>>1])};case 2:return function(e){return this.fromWireType((c?J:L)[e>>2])};default:throw new TypeError("Unknown integer type: "+a);}}
function yc(a,b){var c=ob[a];void 0===c&&R(b+" has unknown type "+nc(a));return c}function Yb(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}function zc(a,b){switch(b){case 2:return function(c){return this.fromWireType(O[c>>2])};case 3:return function(c){return this.fromWireType(Ka[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function Ac(a,b,c){switch(b){case 0:return c?function(e){return Ha[e]}:function(e){return C[e]};case 1:return c?function(e){return Ia[e>>1]}:function(e){return Ja[e>>1]};case 2:return c?function(e){return J[e>>2]}:function(e){return L[e>>2]};default:throw new TypeError("Unknown integer type: "+a);}}
var ka=(a,b,c,e)=>{if(!(0<e))return 0;var f=c;e=c+e-1;for(var k=0;k<a.length;++k){var l=a.charCodeAt(k);if(55296<=l&&57343>=l){var m=a.charCodeAt(++k);l=65536+((l&1023)<<10)|m&1023}if(127>=l){if(c>=e)break;b[c++]=l}else{if(2047>=l){if(c+1>=e)break;b[c++]=192|l>>6}else{if(65535>=l){if(c+2>=e)break;b[c++]=224|l>>12}else{if(c+3>=e)break;b[c++]=240|l>>18;b[c++]=128|l>>12&63}b[c++]=128|l>>6&63}b[c++]=128|l&63}}b[c]=0;return c-f},ja=a=>{for(var b=0,c=0;c<a.length;++c){var e=a.charCodeAt(c);127>=e?b++:2047>=
e?b+=2:55296<=e&&57343>=e?(b+=4,++c):b+=3}return b},Bc="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0,Cc=(a,b)=>{var c=a>>1;for(var e=c+b/2;!(c>=e)&&Ja[c];)++c;c<<=1;if(32<c-a&&Bc)return Bc.decode(C.subarray(a,c));c="";for(e=0;!(e>=b/2);++e){var f=Ia[a+2*e>>1];if(0==f)break;c+=String.fromCharCode(f)}return c},Dc=(a,b,c)=>{void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var e=b;c=c<2*a.length?c/2:a.length;for(var f=0;f<c;++f)Ia[b>>1]=a.charCodeAt(f),b+=2;Ia[b>>1]=0;return b-e},
Ec=a=>2*a.length,Fc=(a,b)=>{for(var c=0,e="";!(c>=b/4);){var f=J[a+4*c>>2];if(0==f)break;++c;65536<=f?(f-=65536,e+=String.fromCharCode(55296|f>>10,56320|f&1023)):e+=String.fromCharCode(f)}return e},Gc=(a,b,c)=>{void 0===c&&(c=2147483647);if(4>c)return 0;var e=b;c=e+c-4;for(var f=0;f<a.length;++f){var k=a.charCodeAt(f);if(55296<=k&&57343>=k){var l=a.charCodeAt(++f);k=65536+((k&1023)<<10)|l&1023}J[b>>2]=k;b+=4;if(b+4>c)break}J[b>>2]=0;return b-e},Hc=a=>{for(var b=0,c=0;c<a.length;++c){var e=a.charCodeAt(c);
55296<=e&&57343>=e&&++c;b+=4}return b},Ic={};function Jc(a){var b=Ic[a];return void 0===b?Q(a):b}var Kc=[];
function Lc(){function a(b){b.$$$embind_global$$$=b;var c="object"==typeof $$$embind_global$$$&&b.$$$embind_global$$$==b;c||delete b.$$$embind_global$$$;return c}if("object"==typeof globalThis)return globalThis;if("object"==typeof $$$embind_global$$$)return $$$embind_global$$$;"object"==typeof global&&a(global)?$$$embind_global$$$=global:"object"==typeof self&&a(self)&&($$$embind_global$$$=self);if("object"==typeof $$$embind_global$$$)return $$$embind_global$$$;throw Error("unable to get global object.");
}function Mc(a){var b=Kc.length;Kc.push(a);return b}function Nc(a,b){for(var c=Array(a),e=0;e<a;++e)c[e]=yc(L[b+4*e>>2],"parameter "+e);return c}var Oc=[];function Pc(a){var b=Array(a+1);return function(c,e,f){b[0]=c;for(var k=0;k<a;++k){var l=yc(L[e+4*k>>2],"parameter "+k);b[k+1]=l.readValueFromPointer(f);f+=l.argPackAdvance}c=new (c.bind.apply(c,b));return $b(c)}}var Qc={};
function Rc(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,e){b.vertexAttribDivisorANGLE(c,e)},a.drawArraysInstanced=function(c,e,f,k){b.drawArraysInstancedANGLE(c,e,f,k)},a.drawElementsInstanced=function(c,e,f,k,l){b.drawElementsInstancedANGLE(c,e,f,k,l)})}
function Sc(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function Tc(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,e){b.drawBuffersWEBGL(c,e)})}
var Uc=1,Vc=[],Wc=[],Xc=[],Yc=[],ea=[],Zc=[],$c=[],ia=[],ad=[],bd=[],cd={},dd={},fd=4;function S(a){gd||(gd=a)}function da(a){for(var b=Uc++,c=a.length;c<b;c++)a[c]=null;return b}function fa(a,b){a.Vd||(a.Vd=a.getContext,a.getContext=function(e,f){f=a.Vd(e,f);return"webgl"==e==f instanceof WebGLRenderingContext?f:null});var c=1<b.majorVersion?a.getContext("webgl2",b):a.getContext("webgl",b);return c?hd(c,b):0}
function hd(a,b){var c=da(ia),e={handle:c,attributes:b,version:b.majorVersion,Qd:a};a.canvas&&(a.canvas.Ke=e);ia[c]=e;("undefined"==typeof b.Ve||b.Ve)&&jd(e);return c}function ha(a){w=ia[a];r.rf=V=w&&w.Qd;return!(a&&!V)}
function jd(a){a||(a=w);if(!a.cf){a.cf=!0;var b=a.Qd;Rc(b);Sc(b);Tc(b);b.Be=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.Fe=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");2<=a.version&&(b.Ce=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.Ce)b.Ce=b.getExtension("EXT_disjoint_timer_query");b.sf=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}
var w,gd;function kd(a){V.bindVertexArray($c[a])}function ld(a,b){for(var c=0;c<a;c++){var e=J[b+4*c>>2];V.deleteVertexArray($c[e]);$c[e]=null}}var md=[];function nd(a,b,c,e){V.drawElements(a,b,c,e)}function od(a,b,c,e){for(var f=0;f<a;f++){var k=V[c](),l=k&&da(e);k?(k.name=l,e[l]=k):S(1282);J[b+4*f>>2]=l}}function pd(a,b){od(a,b,"createVertexArray",$c)}
function qd(a,b,c){if(b){var e=void 0;switch(a){case 36346:e=1;break;case 36344:0!=c&&1!=c&&S(1280);return;case 34814:case 36345:e=0;break;case 34466:var f=V.getParameter(34467);e=f?f.length:0;break;case 33309:if(2>w.version){S(1282);return}e=2*(V.getSupportedExtensions()||[]).length;break;case 33307:case 33308:if(2>w.version){S(1280);return}e=33307==a?3:0}if(void 0===e)switch(f=V.getParameter(a),typeof f){case "number":e=f;break;case "boolean":e=f?1:0;break;case "string":S(1280);return;case "object":if(null===
f)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:e=0;break;default:S(1280);return}else{if(f instanceof Float32Array||f instanceof Uint32Array||f instanceof Int32Array||f instanceof Array){for(a=0;a<f.length;++a)switch(c){case 0:J[b+4*a>>2]=f[a];break;case 2:O[b+4*a>>2]=f[a];break;case 4:Ha[b+a>>0]=f[a]?1:0}return}try{e=f.name|0}catch(k){S(1280);
Ca("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+k+")");return}}break;default:S(1280);Ca("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+f+" of type "+typeof f+"!");return}switch(c){case 1:c=e;L[b>>2]=c;L[b+4>>2]=(c-L[b>>2])/4294967296;break;case 0:J[b>>2]=e;break;case 2:O[b>>2]=e;break;case 4:Ha[b>>0]=e?1:0}}else S(1281)}var sd=a=>{var b=ja(a)+1,c=rd(b);c&&ka(a,C,c,b);return c};
function td(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}function ud(a){a-=5120;return 0==a?Ha:1==a?C:2==a?Ia:4==a?J:6==a?O:5==a||28922==a||28520==a||30779==a||30782==a?L:Ja}function vd(a,b,c,e,f){a=ud(a);var k=31-Math.clz32(a.BYTES_PER_ELEMENT),l=fd;return a.subarray(f>>k,f+e*(c*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[b-6402]||1)*(1<<k)+l-1&-l)>>k)}
function Z(a){var b=V.Se;if(b){var c=b.fe[a];"number"==typeof c&&(b.fe[a]=c=V.getUniformLocation(b,b.Ie[a]+(0<c?"["+c+"]":"")));return c}S(1282)}
var wd=[],xd=[],yd={},Ad=()=>{if(!zd){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:na||"./this.program"},b;for(b in yd)void 0===yd[b]?delete a[b]:a[b]=yd[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);zd=c}return zd},zd,Bd=[null,[],[]],Cd=a=>0===a%4&&(0!==a%100||0===a%400),Dd=[31,29,31,30,31,30,31,31,30,31,30,31],Ed=[31,28,31,30,31,30,31,31,30,31,30,31];
function Fd(a){var b=Array(ja(a)+1);ka(a,b,0,b.length);return b}
var Gd=(a,b,c,e)=>{function f(u,E,H){for(u="number"==typeof u?u.toString():u||"";u.length<E;)u=H[0]+u;return u}function k(u,E){return f(u,E,"0")}function l(u,E){function H(ba){return 0>ba?-1:0<ba?1:0}var T;0===(T=H(u.getFullYear()-E.getFullYear()))&&0===(T=H(u.getMonth()-E.getMonth()))&&(T=H(u.getDate()-E.getDate()));return T}function m(u){switch(u.getDay()){case 0:return new Date(u.getFullYear()-1,11,29);case 1:return u;case 2:return new Date(u.getFullYear(),0,3);case 3:return new Date(u.getFullYear(),
0,2);case 4:return new Date(u.getFullYear(),0,1);case 5:return new Date(u.getFullYear()-1,11,31);case 6:return new Date(u.getFullYear()-1,11,30)}}function q(u){var E=u.Wd;for(u=new Date((new Date(u.Xd+1900,0,1)).getTime());0<E;){var H=u.getMonth(),T=(Cd(u.getFullYear())?Dd:Ed)[H];if(E>T-u.getDate())E-=T-u.getDate()+1,u.setDate(1),11>H?u.setMonth(H+1):(u.setMonth(0),u.setFullYear(u.getFullYear()+1));else{u.setDate(u.getDate()+E);break}}H=new Date(u.getFullYear()+1,0,4);E=m(new Date(u.getFullYear(),
0,4));H=m(H);return 0>=l(E,u)?0>=l(H,u)?u.getFullYear()+1:u.getFullYear():u.getFullYear()-1}var x=J[e+40>>2];e={pf:J[e>>2],nf:J[e+4>>2],pe:J[e+8>>2],ye:J[e+12>>2],qe:J[e+16>>2],Xd:J[e+20>>2],Rd:J[e+24>>2],Wd:J[e+28>>2],vf:J[e+32>>2],mf:J[e+36>>2],qf:x?x?jb(C,x):"":""};c=c?jb(C,c):"";x={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y",
"%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var y in x)c=c.replace(new RegExp(y,"g"),x[y]);var B="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),D="January February March April May June July August September October November December".split(" ");x={"%a":u=>B[u.Rd].substring(0,3),"%A":u=>B[u.Rd],"%b":u=>D[u.qe].substring(0,3),"%B":u=>D[u.qe],"%C":u=>k((u.Xd+1900)/
100|0,2),"%d":u=>k(u.ye,2),"%e":u=>f(u.ye,2," "),"%g":u=>q(u).toString().substring(2),"%G":u=>q(u),"%H":u=>k(u.pe,2),"%I":u=>{u=u.pe;0==u?u=12:12<u&&(u-=12);return k(u,2)},"%j":u=>{for(var E=0,H=0;H<=u.qe-1;E+=(Cd(u.Xd+1900)?Dd:Ed)[H++]);return k(u.ye+E,3)},"%m":u=>k(u.qe+1,2),"%M":u=>k(u.nf,2),"%n":()=>"\n","%p":u=>0<=u.pe&&12>u.pe?"AM":"PM","%S":u=>k(u.pf,2),"%t":()=>"\t","%u":u=>u.Rd||7,"%U":u=>k(Math.floor((u.Wd+7-u.Rd)/7),2),"%V":u=>{var E=Math.floor((u.Wd+7-(u.Rd+6)%7)/7);2>=(u.Rd+371-u.Wd-
2)%7&&E++;if(E)53==E&&(H=(u.Rd+371-u.Wd)%7,4==H||3==H&&Cd(u.Xd)||(E=1));else{E=52;var H=(u.Rd+7-u.Wd-1)%7;(4==H||5==H&&Cd(u.Xd%400-1))&&E++}return k(E,2)},"%w":u=>u.Rd,"%W":u=>k(Math.floor((u.Wd+7-(u.Rd+6)%7)/7),2),"%y":u=>(u.Xd+1900).toString().substring(2),"%Y":u=>u.Xd+1900,"%z":u=>{u=u.mf;var E=0<=u;u=Math.abs(u)/60;return(E?"+":"-")+String("0000"+(u/60*100+u%60)).slice(-4)},"%Z":u=>u.qf,"%%":()=>"%"};c=c.replace(/%%/g,"\x00\x00");for(y in x)c.includes(y)&&(c=c.replace(new RegExp(y,"g"),x[y](e)));
c=c.replace(/\0\0/g,"%");y=Fd(c);if(y.length>b)return 0;Ha.set(y,a);return y.length-1};qb=r.InternalError=class extends Error{constructor(a){super(a);this.name="InternalError"}};for(var Hd=Array(256),Id=0;256>Id;++Id)Hd[Id]=String.fromCharCode(Id);vb=Hd;wb=r.BindingError=class extends Error{constructor(a){super(a);this.name="BindingError"}};
Qb.prototype.isAliasOf=function(a){if(!(this instanceof Qb&&a instanceof Qb))return!1;var b=this.jd.Jd.Hd,c=this.jd.Gd,e=a.jd.Jd.Hd;for(a=a.jd.Gd;b.Md;)c=b.ge(c),b=b.Md;for(;e.Md;)a=e.ge(a),e=e.Md;return b===e&&c===a};
Qb.prototype.clone=function(){this.jd.Gd||yb(this);if(this.jd.ee)return this.jd.count.value+=1,this;var a=Pb,b=Object,c=b.create,e=Object.getPrototypeOf(this),f=this.jd;a=a(c.call(b,e,{jd:{value:{count:f.count,ae:f.ae,ee:f.ee,Gd:f.Gd,Jd:f.Jd,Ld:f.Ld,Pd:f.Pd}}}));a.jd.count.value+=1;a.jd.ae=!1;return a};Qb.prototype["delete"]=function(){this.jd.Gd||yb(this);this.jd.ae&&!this.jd.ee&&R("Object already scheduled for deletion");Ab(this);Bb(this.jd);this.jd.ee||(this.jd.Ld=void 0,this.jd.Gd=void 0)};
Qb.prototype.isDeleted=function(){return!this.jd.Gd};Qb.prototype.deleteLater=function(){this.jd.Gd||yb(this);this.jd.ae&&!this.jd.ee&&R("Object already scheduled for deletion");Jb.push(this);1===Jb.length&&Lb&&Lb(Kb);this.jd.ae=!0;return this};r.getInheritedInstanceCount=function(){return Object.keys(Mb).length};r.getLiveInheritedInstances=function(){var a=[],b;for(b in Mb)Mb.hasOwnProperty(b)&&a.push(Mb[b]);return a};r.flushPendingDeletes=Kb;r.setDelayFunction=function(a){Lb=a;Jb.length&&Lb&&Lb(Kb)};
bc.prototype.Ye=function(a){this.Ge&&(a=this.Ge(a));return a};bc.prototype.Ae=function(a){this.Td&&this.Td(a)};bc.prototype.argPackAdvance=8;bc.prototype.readValueFromPointer=mb;bc.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
bc.prototype.fromWireType=function(a){function b(){return this.le?Ob(this.Hd.be,{Jd:this.ef,Gd:c,Pd:this,Ld:a}):Ob(this.Hd.be,{Jd:this,Gd:a})}var c=this.Ye(a);if(!c)return this.Ae(a),null;var e=Nb(this.Hd,c);if(void 0!==e){if(0===e.jd.count.value)return e.jd.Gd=c,e.jd.Ld=a,e.clone();e=e.clone();this.Ae(a);return e}e=this.Hd.Xe(c);e=Ib[e];if(!e)return b.call(this);e=this.ke?e.Re:e.pointerType;var f=Cb(c,this.Hd,e.Hd);return null===f?b.call(this):this.le?Ob(e.Hd.be,{Jd:e,Gd:f,Pd:this,Ld:a}):Ob(e.Hd.be,
{Jd:e,Gd:f})};mc=r.UnboundTypeError=function(a,b){var c=Sb(b,function(e){this.name=b;this.message=e;e=Error(e).stack;void 0!==e&&(this.stack=this.toString()+"\n"+e.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(a.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:`${this.name}: ${this.message}`};return c}(Error,"UnboundTypeError");
Object.assign(tc.prototype,{get(a){return this.Sd[a]},has(a){return void 0!==this.Sd[a]},re(a){var b=this.Ee.pop()||this.Sd.length;this.Sd[b]=a;return b},se(a){this.Sd[a]=void 0;this.Ee.push(a)}});uc.Sd.push({value:void 0},{value:null},{value:!0},{value:!1});uc.Vd=uc.Sd.length;r.count_emval_handles=function(){for(var a=0,b=uc.Vd;b<uc.Sd.length;++b)void 0!==uc.Sd[b]&&++a;return a};for(var V,Jd=0;32>Jd;++Jd)md.push(Array(Jd));var Kd=new Float32Array(288);
for(Jd=0;288>Jd;++Jd)wd[Jd]=Kd.subarray(0,Jd+1);var Ld=new Int32Array(288);for(Jd=0;288>Jd;++Jd)xd[Jd]=Ld.subarray(0,Jd+1);
var Zd={G:function(a,b,c){(new eb(a)).Vd(b,c);fb=a;hb++;throw fb;},T:function(){return 0},rb:()=>{},tb:function(){return 0},pb:()=>{},ub:function(){},qb:()=>{},C:function(a){var b=kb[a];delete kb[a];var c=b.xe,e=b.Td,f=b.De,k=f.map(l=>l.af).concat(f.map(l=>l.jf));sb([a],k,l=>{var m={};f.forEach((q,x)=>{var y=l[x],B=q.Ze,D=q.$e,u=l[x+f.length],E=q.hf,H=q.kf;m[q.We]={read:T=>y.fromWireType(B(D,T)),write:(T,ba)=>{var X=[];E(H,T,u.toWireType(X,ba));lb(X)}}});return[{name:b.name,fromWireType:function(q){var x=
{},y;for(y in m)x[y]=m[y].read(q);e(q);return x},toWireType:function(q,x){for(var y in m)if(!(y in x))throw new TypeError(`Missing field: "${y}"`);var B=c();for(y in m)m[y].write(B,x[y]);null!==q&&q.push(e,B);return B},argPackAdvance:8,readValueFromPointer:mb,Od:e}]})},jb:function(){},yb:function(a,b,c,e,f){var k=ub(c);b=Q(b);tb(a,{name:b,fromWireType:function(l){return!!l},toWireType:function(l,m){return m?e:f},argPackAdvance:8,readValueFromPointer:function(l){if(1===c)var m=Ha;else if(2===c)m=Ia;
else if(4===c)m=J;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(m[l>>k])},Od:null})},l:function(a,b,c,e,f,k,l,m,q,x,y,B,D){y=Q(y);k=lc(f,k);m&&(m=lc(l,m));x&&(x=lc(q,x));D=lc(B,D);var u=Rb(y);Ub(u,function(){qc(`Cannot construct ${y} due to unbound types`,[e])});sb([a,b,c],e?[e]:[],function(E){E=E[0];if(e){var H=E.Hd;var T=H.be}else T=Qb.prototype;E=Sb(u,function(){if(Object.getPrototypeOf(this)!==ba)throw new wb("Use 'new' to construct "+y);if(void 0===X.Ud)throw new wb(y+
" has no accessible constructor");var La=X.Ud[arguments.length];if(void 0===La)throw new wb(`Tried to invoke ctor of ${y} with invalid number of parameters (${arguments.length}) - expected (${Object.keys(X.Ud).toString()}) parameters instead!`);return La.apply(this,arguments)});var ba=Object.create(T,{constructor:{value:E}});E.prototype=ba;var X=new Vb(y,E,ba,D,H,k,m,x);X.Md&&(void 0===X.Md.he&&(X.Md.he=[]),X.Md.he.push(X));H=new bc(y,X,!0,!1,!1);T=new bc(y+"*",X,!1,!1,!1);var ua=new bc(y+" const*",
X,!1,!0,!1);Ib[a]={pointerType:T,Re:ua};cc(u,E);return[H,T,ua]})},e:function(a,b,c,e,f,k,l){var m=sc(c,e);b=Q(b);k=lc(f,k);sb([],[a],function(q){function x(){qc(`Cannot call ${y} due to unbound types`,m)}q=q[0];var y=`${q.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);var B=q.Hd.constructor;void 0===B[b]?(x.Zd=c-1,B[b]=x):(Tb(B,b,y),B[b].Kd[c-1]=x);sb([],m,function(D){D=[D[0],null].concat(D.slice(1));D=rc(y,D,null,k,l);void 0===B[b].Kd?(D.Zd=c-1,B[b]=D):B[b].Kd[c-1]=D;if(q.Hd.he)for(const u of q.Hd.he)u.constructor.hasOwnProperty(b)||
(u.constructor[b]=D);return[]});return[]})},A:function(a,b,c,e,f,k){var l=sc(b,c);f=lc(e,f);sb([],[a],function(m){m=m[0];var q=`constructor ${m.name}`;void 0===m.Hd.Ud&&(m.Hd.Ud=[]);if(void 0!==m.Hd.Ud[b-1])throw new wb(`Cannot register multiple constructors with identical number of parameters (${b-1}) for class '${m.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);m.Hd.Ud[b-1]=()=>{qc(`Cannot construct ${m.name} due to unbound types`,l)};
sb([],l,function(x){x.splice(1,0,null);m.Hd.Ud[b-1]=rc(q,x,null,f,k);return[]});return[]})},a:function(a,b,c,e,f,k,l,m){var q=sc(c,e);b=Q(b);k=lc(f,k);sb([],[a],function(x){function y(){qc(`Cannot call ${B} due to unbound types`,q)}x=x[0];var B=`${x.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);m&&x.Hd.ff.push(b);var D=x.Hd.be,u=D[b];void 0===u||void 0===u.Kd&&u.className!==x.name&&u.Zd===c-2?(y.Zd=c-2,y.className=x.name,D[b]=y):(Tb(D,b,B),D[b].Kd[c-2]=y);sb([],q,function(E){E=rc(B,E,
x,k,l);void 0===D[b].Kd?(E.Zd=c-2,D[b]=E):D[b].Kd[c-2]=E;return[]});return[]})},s:function(a,b,c){a=Q(a);sb([],[b],function(e){e=e[0];r[a]=e.fromWireType(c);return[]})},xb:function(a,b){b=Q(b);tb(a,{name:b,fromWireType:function(c){var e=wc(c);vc(c);return e},toWireType:function(c,e){return $b(e)},argPackAdvance:8,readValueFromPointer:mb,Od:null})},i:function(a,b,c,e){function f(){}c=ub(c);b=Q(b);f.values={};tb(a,{name:b,constructor:f,fromWireType:function(k){return this.constructor.values[k]},toWireType:function(k,
l){return l.value},argPackAdvance:8,readValueFromPointer:xc(b,c,e),Od:null});Ub(b,f)},b:function(a,b,c){var e=yc(a,"enum");b=Q(b);a=e.constructor;e=Object.create(e.constructor.prototype,{value:{value:c},constructor:{value:Sb(`${e.name}_${b}`,function(){})}});a.values[c]=e;a[b]=e},W:function(a,b,c){c=ub(c);b=Q(b);tb(a,{name:b,fromWireType:function(e){return e},toWireType:function(e,f){return f},argPackAdvance:8,readValueFromPointer:zc(b,c),Od:null})},u:function(a,b,c,e,f,k){var l=sc(b,c);a=Q(a);f=
lc(e,f);Ub(a,function(){qc(`Cannot call ${a} due to unbound types`,l)},b-1);sb([],l,function(m){m=[m[0],null].concat(m.slice(1));cc(a,rc(a,m,null,f,k),b-1);return[]})},E:function(a,b,c,e,f){b=Q(b);-1===f&&(f=4294967295);f=ub(c);var k=m=>m;if(0===e){var l=32-8*c;k=m=>m<<l>>>l}c=b.includes("unsigned")?function(m,q){return q>>>0}:function(m,q){return q};tb(a,{name:b,fromWireType:k,toWireType:c,argPackAdvance:8,readValueFromPointer:Ac(b,f,0!==e),Od:null})},r:function(a,b,c){function e(k){k>>=2;var l=
L;return new f(l.buffer,l[k+1],l[k])}var f=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=Q(c);tb(a,{name:c,fromWireType:e,argPackAdvance:8,readValueFromPointer:e},{bf:!0})},q:function(a,b,c,e,f,k,l,m,q,x,y,B){c=Q(c);k=lc(f,k);m=lc(l,m);x=lc(q,x);B=lc(y,B);sb([a],[b],function(D){D=D[0];return[new bc(c,D.Hd,!1,!1,!0,D,e,k,m,x,B)]})},V:function(a,b){b=Q(b);var c="std::string"===b;tb(a,{name:b,fromWireType:function(e){var f=L[e>>2],k=e+4;if(c)for(var l=
k,m=0;m<=f;++m){var q=k+m;if(m==f||0==C[q]){l=l?jb(C,l,q-l):"";if(void 0===x)var x=l;else x+=String.fromCharCode(0),x+=l;l=q+1}}else{x=Array(f);for(m=0;m<f;++m)x[m]=String.fromCharCode(C[k+m]);x=x.join("")}pc(e);return x},toWireType:function(e,f){f instanceof ArrayBuffer&&(f=new Uint8Array(f));var k="string"==typeof f;k||f instanceof Uint8Array||f instanceof Uint8ClampedArray||f instanceof Int8Array||R("Cannot pass non-string to std::string");var l=c&&k?ja(f):f.length;var m=rd(4+l+1),q=m+4;L[m>>2]=
l;if(c&&k)ka(f,C,q,l+1);else if(k)for(k=0;k<l;++k){var x=f.charCodeAt(k);255<x&&(pc(q),R("String has UTF-16 code units that do not fit in 8 bits"));C[q+k]=x}else for(k=0;k<l;++k)C[q+k]=f[k];null!==e&&e.push(pc,m);return m},argPackAdvance:8,readValueFromPointer:mb,Od:function(e){pc(e)}})},M:function(a,b,c){c=Q(c);if(2===b){var e=Cc;var f=Dc;var k=Ec;var l=()=>Ja;var m=1}else 4===b&&(e=Fc,f=Gc,k=Hc,l=()=>L,m=2);tb(a,{name:c,fromWireType:function(q){for(var x=L[q>>2],y=l(),B,D=q+4,u=0;u<=x;++u){var E=
q+4+u*b;if(u==x||0==y[E>>m])D=e(D,E-D),void 0===B?B=D:(B+=String.fromCharCode(0),B+=D),D=E+b}pc(q);return B},toWireType:function(q,x){"string"!=typeof x&&R(`Cannot pass non-string to C++ string type ${c}`);var y=k(x),B=rd(4+y+b);L[B>>2]=y>>m;f(x,B+4,y+b);null!==q&&q.push(pc,B);return B},argPackAdvance:8,readValueFromPointer:mb,Od:function(q){pc(q)}})},D:function(a,b,c,e,f,k){kb[a]={name:Q(b),xe:lc(c,e),Td:lc(f,k),De:[]}},d:function(a,b,c,e,f,k,l,m,q,x){kb[a].De.push({We:Q(b),af:c,Ze:lc(e,f),$e:k,
jf:l,hf:lc(m,q),kf:x})},zb:function(a,b){b=Q(b);tb(a,{df:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},wb:()=>!0,lb:()=>{throw Infinity;},F:function(a,b,c){a=wc(a);b=yc(b,"emval::as");var e=[],f=$b(e);L[c>>2]=f;return b.toWireType(e,a)},O:function(a,b,c,e,f){a=Kc[a];b=wc(b);c=Jc(c);var k=[];L[e>>2]=$b(k);return a(b,c,k,f)},w:function(a,b,c,e){a=Kc[a];b=wc(b);c=Jc(c);a(b,c,null,e)},c:vc,K:function(a){if(0===a)return $b(Lc());a=Jc(a);return $b(Lc()[a])},t:function(a,
b){var c=Nc(a,b),e=c[0];b=e.name+"_$"+c.slice(1).map(function(l){return l.name}).join("_")+"$";var f=Oc[b];if(void 0!==f)return f;var k=Array(a-1);f=Mc((l,m,q,x)=>{for(var y=0,B=0;B<a-1;++B)k[B]=c[B+1].readValueFromPointer(x+y),y+=c[B+1].argPackAdvance;l=l[m].apply(l,k);for(B=0;B<a-1;++B)c[B+1].Te&&c[B+1].Te(k[B]);if(!e.df)return e.toWireType(q,l)});return Oc[b]=f},z:function(a,b){a=wc(a);b=wc(b);return $b(a[b])},n:function(a){4<a&&(uc.get(a).He+=1)},J:function(a,b,c,e){a=wc(a);var f=Qc[b];f||(f=
Pc(b),Qc[b]=f);return f(a,c,e)},I:function(){return $b([])},f:function(a){return $b(Jc(a))},H:function(){return $b({})},db:function(a){a=wc(a);return!a},B:function(a){var b=wc(a);lb(b);vc(a)},h:function(a,b,c){a=wc(a);b=wc(b);c=wc(c);a[b]=c},g:function(a,b){a=yc(a,"_emval_take_value");a=a.readValueFromPointer(b);return $b(a)},gb:function(){return-52},hb:function(){},k:()=>{Ea("")},vb:()=>performance.now(),Tc:function(a){V.activeTexture(a)},Uc:function(a,b){V.attachShader(Wc[a],Zc[b])},Vc:function(a,
b,c){V.bindAttribLocation(Wc[a],b,c?jb(C,c):"")},Wc:function(a,b){35051==a?V.ue=b:35052==a&&(V.$d=b);V.bindBuffer(a,Vc[b])},_:function(a,b){V.bindFramebuffer(a,Xc[b])},Xb:function(a,b){V.bindRenderbuffer(a,Yc[b])},Hb:function(a,b){V.bindSampler(a,ad[b])},Xc:function(a,b){V.bindTexture(a,ea[b])},pc:kd,sc:kd,Yc:function(a,b,c,e){V.blendColor(a,b,c,e)},Zc:function(a){V.blendEquation(a)},_c:function(a,b){V.blendFunc(a,b)},Rb:function(a,b,c,e,f,k,l,m,q,x){V.blitFramebuffer(a,b,c,e,f,k,l,m,q,x)},$:function(a,
b,c,e){2<=w.version?c&&b?V.bufferData(a,C,e,c,b):V.bufferData(a,b,e):V.bufferData(a,c?C.subarray(c,c+b):b,e)},aa:function(a,b,c,e){2<=w.version?c&&V.bufferSubData(a,b,C,e,c):V.bufferSubData(a,b,C.subarray(e,e+c))},Yb:function(a){return V.checkFramebufferStatus(a)},Q:function(a){V.clear(a)},Z:function(a,b,c,e){V.clearColor(a,b,c,e)},S:function(a){V.clearStencil(a)},bb:function(a,b,c,e){return V.clientWaitSync(bd[a],b,(c>>>0)+4294967296*e)},ba:function(a,b,c,e){V.colorMask(!!a,!!b,!!c,!!e)},ca:function(a){V.compileShader(Zc[a])},
da:function(a,b,c,e,f,k,l,m){2<=w.version?V.$d||!l?V.compressedTexImage2D(a,b,c,e,f,k,l,m):V.compressedTexImage2D(a,b,c,e,f,k,C,m,l):V.compressedTexImage2D(a,b,c,e,f,k,m?C.subarray(m,m+l):null)},ea:function(a,b,c,e,f,k,l,m,q){2<=w.version?V.$d||!m?V.compressedTexSubImage2D(a,b,c,e,f,k,l,m,q):V.compressedTexSubImage2D(a,b,c,e,f,k,l,C,q,m):V.compressedTexSubImage2D(a,b,c,e,f,k,l,q?C.subarray(q,q+m):null)},Pb:function(a,b,c,e,f){V.copyBufferSubData(a,b,c,e,f)},fa:function(a,b,c,e,f,k,l,m){V.copyTexSubImage2D(a,
b,c,e,f,k,l,m)},ga:function(){var a=da(Wc),b=V.createProgram();b.name=a;b.oe=b.me=b.ne=0;b.ze=1;Wc[a]=b;return a},ha:function(a){var b=da(Zc);Zc[b]=V.createShader(a);return b},ia:function(a){V.cullFace(a)},ja:function(a,b){for(var c=0;c<a;c++){var e=J[b+4*c>>2],f=Vc[e];f&&(V.deleteBuffer(f),f.name=0,Vc[e]=null,e==V.ue&&(V.ue=0),e==V.$d&&(V.$d=0))}},Zb:function(a,b){for(var c=0;c<a;++c){var e=J[b+4*c>>2],f=Xc[e];f&&(V.deleteFramebuffer(f),f.name=0,Xc[e]=null)}},ka:function(a){if(a){var b=Wc[a];b?(V.deleteProgram(b),
b.name=0,Wc[a]=null):S(1281)}},_b:function(a,b){for(var c=0;c<a;c++){var e=J[b+4*c>>2],f=Yc[e];f&&(V.deleteRenderbuffer(f),f.name=0,Yc[e]=null)}},Ib:function(a,b){for(var c=0;c<a;c++){var e=J[b+4*c>>2],f=ad[e];f&&(V.deleteSampler(f),f.name=0,ad[e]=null)}},la:function(a){if(a){var b=Zc[a];b?(V.deleteShader(b),Zc[a]=null):S(1281)}},Qb:function(a){if(a){var b=bd[a];b?(V.deleteSync(b),b.name=0,bd[a]=null):S(1281)}},ma:function(a,b){for(var c=0;c<a;c++){var e=J[b+4*c>>2],f=ea[e];f&&(V.deleteTexture(f),
f.name=0,ea[e]=null)}},qc:ld,tc:ld,na:function(a){V.depthMask(!!a)},oa:function(a){V.disable(a)},pa:function(a){V.disableVertexAttribArray(a)},qa:function(a,b,c){V.drawArrays(a,b,c)},nc:function(a,b,c,e){V.drawArraysInstanced(a,b,c,e)},lc:function(a,b,c,e,f){V.Be.drawArraysInstancedBaseInstanceWEBGL(a,b,c,e,f)},jc:function(a,b){for(var c=md[a],e=0;e<a;e++)c[e]=J[b+4*e>>2];V.drawBuffers(c)},ra:nd,oc:function(a,b,c,e,f){V.drawElementsInstanced(a,b,c,e,f)},mc:function(a,b,c,e,f,k,l){V.Be.drawElementsInstancedBaseVertexBaseInstanceWEBGL(a,
b,c,e,f,k,l)},dc:function(a,b,c,e,f,k){nd(a,e,f,k)},sa:function(a){V.enable(a)},ta:function(a){V.enableVertexAttribArray(a)},Nb:function(a,b){return(a=V.fenceSync(a,b))?(b=da(bd),a.name=b,bd[b]=a,b):0},ua:function(){V.finish()},va:function(){V.flush()},$b:function(a,b,c,e){V.framebufferRenderbuffer(a,b,c,Yc[e])},ac:function(a,b,c,e,f){V.framebufferTexture2D(a,b,c,ea[e],f)},wa:function(a){V.frontFace(a)},xa:function(a,b){od(a,b,"createBuffer",Vc)},bc:function(a,b){od(a,b,"createFramebuffer",Xc)},cc:function(a,
b){od(a,b,"createRenderbuffer",Yc)},Jb:function(a,b){od(a,b,"createSampler",ad)},ya:function(a,b){od(a,b,"createTexture",ea)},rc:pd,uc:pd,Tb:function(a){V.generateMipmap(a)},za:function(a,b,c){c?J[c>>2]=V.getBufferParameter(a,b):S(1281)},Aa:function(){var a=V.getError()||gd;gd=0;return a},Ba:function(a,b){qd(a,b,2)},Ub:function(a,b,c,e){a=V.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;J[e>>2]=a},L:function(a,b){qd(a,b,0)},Ca:function(a,
b,c,e){a=V.getProgramInfoLog(Wc[a]);null===a&&(a="(unknown error)");b=0<b&&e?ka(a,C,e,b):0;c&&(J[c>>2]=b)},Da:function(a,b,c){if(c)if(a>=Uc)S(1281);else if(a=Wc[a],35716==b)a=V.getProgramInfoLog(a),null===a&&(a="(unknown error)"),J[c>>2]=a.length+1;else if(35719==b){if(!a.oe)for(b=0;b<V.getProgramParameter(a,35718);++b)a.oe=Math.max(a.oe,V.getActiveUniform(a,b).name.length+1);J[c>>2]=a.oe}else if(35722==b){if(!a.me)for(b=0;b<V.getProgramParameter(a,35721);++b)a.me=Math.max(a.me,V.getActiveAttrib(a,
b).name.length+1);J[c>>2]=a.me}else if(35381==b){if(!a.ne)for(b=0;b<V.getProgramParameter(a,35382);++b)a.ne=Math.max(a.ne,V.getActiveUniformBlockName(a,b).length+1);J[c>>2]=a.ne}else J[c>>2]=V.getProgramParameter(a,b);else S(1281)},Vb:function(a,b,c){c?J[c>>2]=V.getRenderbufferParameter(a,b):S(1281)},Ea:function(a,b,c,e){a=V.getShaderInfoLog(Zc[a]);null===a&&(a="(unknown error)");b=0<b&&e?ka(a,C,e,b):0;c&&(J[c>>2]=b)},Eb:function(a,b,c,e){a=V.getShaderPrecisionFormat(a,b);J[c>>2]=a.rangeMin;J[c+4>>
2]=a.rangeMax;J[e>>2]=a.precision},Fa:function(a,b,c){c?35716==b?(a=V.getShaderInfoLog(Zc[a]),null===a&&(a="(unknown error)"),J[c>>2]=a?a.length+1:0):35720==b?(a=V.getShaderSource(Zc[a]),J[c>>2]=a?a.length+1:0):J[c>>2]=V.getShaderParameter(Zc[a],b):S(1281)},P:function(a){var b=cd[a];if(!b){switch(a){case 7939:b=V.getSupportedExtensions()||[];b=b.concat(b.map(function(e){return"GL_"+e}));b=sd(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=V.getParameter(a))||S(1280);b=b&&sd(b);break;
case 7938:b=V.getParameter(7938);b=2<=w.version?"OpenGL ES 3.0 ("+b+")":"OpenGL ES 2.0 ("+b+")";b=sd(b);break;case 35724:b=V.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=sd(b);break;default:S(1280)}cd[a]=b}return b},ab:function(a,b){if(2>w.version)return S(1282),0;var c=dd[a];if(c)return 0>b||b>=c.length?(S(1281),0):c[b];switch(a){case 7939:return c=V.getSupportedExtensions()||[],
c=c.concat(c.map(function(e){return"GL_"+e})),c=c.map(function(e){return sd(e)}),c=dd[a]=c,0>b||b>=c.length?(S(1281),0):c[b];default:return S(1280),0}},Ga:function(a,b){b=b?jb(C,b):"";if(a=Wc[a]){var c=a,e=c.fe,f=c.Je,k;if(!e)for(c.fe=e={},c.Ie={},k=0;k<V.getProgramParameter(c,35718);++k){var l=V.getActiveUniform(c,k);var m=l.name;l=l.size;var q=td(m);q=0<q?m.slice(0,q):m;var x=c.ze;c.ze+=l;f[q]=[l,x];for(m=0;m<l;++m)e[x]=m,c.Ie[x++]=q}c=a.fe;e=0;f=b;k=td(b);0<k&&(e=parseInt(b.slice(k+1))>>>0,f=b.slice(0,
k));if((f=a.Je[f])&&e<f[0]&&(e+=f[1],c[e]=c[e]||V.getUniformLocation(a,b)))return e}else S(1281);return-1},Fb:function(a,b,c){for(var e=md[b],f=0;f<b;f++)e[f]=J[c+4*f>>2];V.invalidateFramebuffer(a,e)},Gb:function(a,b,c,e,f,k,l){for(var m=md[b],q=0;q<b;q++)m[q]=J[c+4*q>>2];V.invalidateSubFramebuffer(a,m,e,f,k,l)},Ob:function(a){return V.isSync(bd[a])},Ha:function(a){return(a=ea[a])?V.isTexture(a):0},Ia:function(a){V.lineWidth(a)},Ja:function(a){a=Wc[a];V.linkProgram(a);a.fe=0;a.Je={}},hc:function(a,
b,c,e,f,k){V.Fe.multiDrawArraysInstancedBaseInstanceWEBGL(a,J,b>>2,J,c>>2,J,e>>2,L,f>>2,k)},ic:function(a,b,c,e,f,k,l,m){V.Fe.multiDrawElementsInstancedBaseVertexBaseInstanceWEBGL(a,J,b>>2,c,J,e>>2,J,f>>2,J,k>>2,L,l>>2,m)},Ka:function(a,b){3317==a&&(fd=b);V.pixelStorei(a,b)},kc:function(a){V.readBuffer(a)},La:function(a,b,c,e,f,k,l){if(2<=w.version)if(V.ue)V.readPixels(a,b,c,e,f,k,l);else{var m=ud(k);V.readPixels(a,b,c,e,f,k,m,l>>31-Math.clz32(m.BYTES_PER_ELEMENT))}else(l=vd(k,f,c,e,l))?V.readPixels(a,
b,c,e,f,k,l):S(1280)},Wb:function(a,b,c,e){V.renderbufferStorage(a,b,c,e)},Sb:function(a,b,c,e,f){V.renderbufferStorageMultisample(a,b,c,e,f)},Kb:function(a,b,c){V.samplerParameterf(ad[a],b,c)},Lb:function(a,b,c){V.samplerParameteri(ad[a],b,c)},Mb:function(a,b,c){V.samplerParameteri(ad[a],b,J[c>>2])},Ma:function(a,b,c,e){V.scissor(a,b,c,e)},Na:function(a,b,c,e){for(var f="",k=0;k<b;++k){var l=e?J[e+4*k>>2]:-1,m=J[c+4*k>>2];l=m?jb(C,m,0>l?void 0:l):"";f+=l}V.shaderSource(Zc[a],f)},Oa:function(a,b,
c){V.stencilFunc(a,b,c)},Pa:function(a,b,c,e){V.stencilFuncSeparate(a,b,c,e)},Qa:function(a){V.stencilMask(a)},Ra:function(a,b){V.stencilMaskSeparate(a,b)},Sa:function(a,b,c){V.stencilOp(a,b,c)},Ta:function(a,b,c,e){V.stencilOpSeparate(a,b,c,e)},Ua:function(a,b,c,e,f,k,l,m,q){if(2<=w.version)if(V.$d)V.texImage2D(a,b,c,e,f,k,l,m,q);else if(q){var x=ud(m);V.texImage2D(a,b,c,e,f,k,l,m,x,q>>31-Math.clz32(x.BYTES_PER_ELEMENT))}else V.texImage2D(a,b,c,e,f,k,l,m,null);else V.texImage2D(a,b,c,e,f,k,l,m,q?
vd(m,l,e,f,q):null)},Va:function(a,b,c){V.texParameterf(a,b,c)},Wa:function(a,b,c){V.texParameterf(a,b,O[c>>2])},Xa:function(a,b,c){V.texParameteri(a,b,c)},Ya:function(a,b,c){V.texParameteri(a,b,J[c>>2])},ec:function(a,b,c,e,f){V.texStorage2D(a,b,c,e,f)},Za:function(a,b,c,e,f,k,l,m,q){if(2<=w.version)if(V.$d)V.texSubImage2D(a,b,c,e,f,k,l,m,q);else if(q){var x=ud(m);V.texSubImage2D(a,b,c,e,f,k,l,m,x,q>>31-Math.clz32(x.BYTES_PER_ELEMENT))}else V.texSubImage2D(a,b,c,e,f,k,l,m,null);else x=null,q&&(x=
vd(m,l,f,k,q)),V.texSubImage2D(a,b,c,e,f,k,l,m,x)},_a:function(a,b){V.uniform1f(Z(a),b)},$a:function(a,b,c){if(2<=w.version)b&&V.uniform1fv(Z(a),O,c>>2,b);else{if(288>=b)for(var e=wd[b-1],f=0;f<b;++f)e[f]=O[c+4*f>>2];else e=O.subarray(c>>2,c+4*b>>2);V.uniform1fv(Z(a),e)}},Pc:function(a,b){V.uniform1i(Z(a),b)},Qc:function(a,b,c){if(2<=w.version)b&&V.uniform1iv(Z(a),J,c>>2,b);else{if(288>=b)for(var e=xd[b-1],f=0;f<b;++f)e[f]=J[c+4*f>>2];else e=J.subarray(c>>2,c+4*b>>2);V.uniform1iv(Z(a),e)}},Rc:function(a,
b,c){V.uniform2f(Z(a),b,c)},Sc:function(a,b,c){if(2<=w.version)b&&V.uniform2fv(Z(a),O,c>>2,2*b);else{if(144>=b)for(var e=wd[2*b-1],f=0;f<2*b;f+=2)e[f]=O[c+4*f>>2],e[f+1]=O[c+(4*f+4)>>2];else e=O.subarray(c>>2,c+8*b>>2);V.uniform2fv(Z(a),e)}},Oc:function(a,b,c){V.uniform2i(Z(a),b,c)},Nc:function(a,b,c){if(2<=w.version)b&&V.uniform2iv(Z(a),J,c>>2,2*b);else{if(144>=b)for(var e=xd[2*b-1],f=0;f<2*b;f+=2)e[f]=J[c+4*f>>2],e[f+1]=J[c+(4*f+4)>>2];else e=J.subarray(c>>2,c+8*b>>2);V.uniform2iv(Z(a),e)}},Mc:function(a,
b,c,e){V.uniform3f(Z(a),b,c,e)},Lc:function(a,b,c){if(2<=w.version)b&&V.uniform3fv(Z(a),O,c>>2,3*b);else{if(96>=b)for(var e=wd[3*b-1],f=0;f<3*b;f+=3)e[f]=O[c+4*f>>2],e[f+1]=O[c+(4*f+4)>>2],e[f+2]=O[c+(4*f+8)>>2];else e=O.subarray(c>>2,c+12*b>>2);V.uniform3fv(Z(a),e)}},Kc:function(a,b,c,e){V.uniform3i(Z(a),b,c,e)},Jc:function(a,b,c){if(2<=w.version)b&&V.uniform3iv(Z(a),J,c>>2,3*b);else{if(96>=b)for(var e=xd[3*b-1],f=0;f<3*b;f+=3)e[f]=J[c+4*f>>2],e[f+1]=J[c+(4*f+4)>>2],e[f+2]=J[c+(4*f+8)>>2];else e=
J.subarray(c>>2,c+12*b>>2);V.uniform3iv(Z(a),e)}},Ic:function(a,b,c,e,f){V.uniform4f(Z(a),b,c,e,f)},Hc:function(a,b,c){if(2<=w.version)b&&V.uniform4fv(Z(a),O,c>>2,4*b);else{if(72>=b){var e=wd[4*b-1],f=O;c>>=2;for(var k=0;k<4*b;k+=4){var l=c+k;e[k]=f[l];e[k+1]=f[l+1];e[k+2]=f[l+2];e[k+3]=f[l+3]}}else e=O.subarray(c>>2,c+16*b>>2);V.uniform4fv(Z(a),e)}},vc:function(a,b,c,e,f){V.uniform4i(Z(a),b,c,e,f)},wc:function(a,b,c){if(2<=w.version)b&&V.uniform4iv(Z(a),J,c>>2,4*b);else{if(72>=b)for(var e=xd[4*b-
1],f=0;f<4*b;f+=4)e[f]=J[c+4*f>>2],e[f+1]=J[c+(4*f+4)>>2],e[f+2]=J[c+(4*f+8)>>2],e[f+3]=J[c+(4*f+12)>>2];else e=J.subarray(c>>2,c+16*b>>2);V.uniform4iv(Z(a),e)}},xc:function(a,b,c,e){if(2<=w.version)b&&V.uniformMatrix2fv(Z(a),!!c,O,e>>2,4*b);else{if(72>=b)for(var f=wd[4*b-1],k=0;k<4*b;k+=4)f[k]=O[e+4*k>>2],f[k+1]=O[e+(4*k+4)>>2],f[k+2]=O[e+(4*k+8)>>2],f[k+3]=O[e+(4*k+12)>>2];else f=O.subarray(e>>2,e+16*b>>2);V.uniformMatrix2fv(Z(a),!!c,f)}},yc:function(a,b,c,e){if(2<=w.version)b&&V.uniformMatrix3fv(Z(a),
!!c,O,e>>2,9*b);else{if(32>=b)for(var f=wd[9*b-1],k=0;k<9*b;k+=9)f[k]=O[e+4*k>>2],f[k+1]=O[e+(4*k+4)>>2],f[k+2]=O[e+(4*k+8)>>2],f[k+3]=O[e+(4*k+12)>>2],f[k+4]=O[e+(4*k+16)>>2],f[k+5]=O[e+(4*k+20)>>2],f[k+6]=O[e+(4*k+24)>>2],f[k+7]=O[e+(4*k+28)>>2],f[k+8]=O[e+(4*k+32)>>2];else f=O.subarray(e>>2,e+36*b>>2);V.uniformMatrix3fv(Z(a),!!c,f)}},zc:function(a,b,c,e){if(2<=w.version)b&&V.uniformMatrix4fv(Z(a),!!c,O,e>>2,16*b);else{if(18>=b){var f=wd[16*b-1],k=O;e>>=2;for(var l=0;l<16*b;l+=16){var m=e+l;f[l]=
k[m];f[l+1]=k[m+1];f[l+2]=k[m+2];f[l+3]=k[m+3];f[l+4]=k[m+4];f[l+5]=k[m+5];f[l+6]=k[m+6];f[l+7]=k[m+7];f[l+8]=k[m+8];f[l+9]=k[m+9];f[l+10]=k[m+10];f[l+11]=k[m+11];f[l+12]=k[m+12];f[l+13]=k[m+13];f[l+14]=k[m+14];f[l+15]=k[m+15]}}else f=O.subarray(e>>2,e+64*b>>2);V.uniformMatrix4fv(Z(a),!!c,f)}},Ac:function(a){a=Wc[a];V.useProgram(a);V.Se=a},Bc:function(a,b){V.vertexAttrib1f(a,b)},Cc:function(a,b){V.vertexAttrib2f(a,O[b>>2],O[b+4>>2])},Dc:function(a,b){V.vertexAttrib3f(a,O[b>>2],O[b+4>>2],O[b+8>>2])},
Ec:function(a,b){V.vertexAttrib4f(a,O[b>>2],O[b+4>>2],O[b+8>>2],O[b+12>>2])},fc:function(a,b){V.vertexAttribDivisor(a,b)},gc:function(a,b,c,e,f){V.vertexAttribIPointer(a,b,c,e,f)},Fc:function(a,b,c,e,f,k){V.vertexAttribPointer(a,b,c,!!e,f,k)},Gc:function(a,b,c,e){V.viewport(a,b,c,e)},cb:function(a,b,c,e){V.waitSync(bd[a],b,(c>>>0)+4294967296*e)},mb:a=>{var b=C.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var e=b*(1+.2/c);e=Math.min(e,a+100663296);var f=Math;e=Math.max(a,e);a:{f=f.min.call(f,
2147483648,e+(65536-e%65536)%65536)-Fa.buffer.byteLength+65535>>>16;try{Fa.grow(f);Ma();var k=1;break a}catch(l){}k=void 0}if(k)return!0}return!1},eb:function(){return w?w.handle:0},nb:(a,b)=>{var c=0;Ad().forEach(function(e,f){var k=b+c;f=L[a+4*f>>2]=k;for(k=0;k<e.length;++k)Ha[f++>>0]=e.charCodeAt(k);Ha[f>>0]=0;c+=e.length+1});return 0},ob:(a,b)=>{var c=Ad();L[a>>2]=c.length;var e=0;c.forEach(function(f){e+=f.length+1});L[b>>2]=e;return 0},Ab:a=>{if(!noExitRuntime){if(r.onExit)r.onExit(a);Ga=!0}oa(a,
new cb(a))},U:()=>52,fb:function(){return 52},sb:()=>52,ib:function(){return 70},R:(a,b,c,e)=>{for(var f=0,k=0;k<c;k++){var l=L[b>>2],m=L[b+4>>2];b+=8;for(var q=0;q<m;q++){var x=C[l+q],y=Bd[a];0===x||10===x?((1===a?Ba:Ca)(jb(y,0)),y.length=0):y.push(x)}f+=m}L[e>>2]=f;return 0},o:Md,m:Nd,j:Od,N:Pd,Y:Qd,X:Rd,x:Sd,y:Td,p:Ud,v:Vd,Bb:Wd,Cb:Xd,Db:Yd,kb:(a,b,c,e)=>Gd(a,b,c,e)};
(function(){function a(c){G=c=c.exports;Fa=G.$c;Ma();P=G.bd;Oa.unshift(G.ad);Ta--;r.monitorRunDependencies&&r.monitorRunDependencies(Ta);if(0==Ta&&(null!==Ua&&(clearInterval(Ua),Ua=null),Va)){var e=Va;Va=null;e()}return c}var b={a:Zd};Ta++;r.monitorRunDependencies&&r.monitorRunDependencies(Ta);if(r.instantiateWasm)try{return r.instantiateWasm(b,a)}catch(c){Ca("Module.instantiateWasm callback failed with error: "+c),ca(c)}bb(b,function(c){a(c.instance)}).catch(ca);return{}})();
var pc=r._free=a=>(pc=r._free=G.cd)(a),rd=r._malloc=a=>(rd=r._malloc=G.dd)(a),oc=a=>(oc=G.ed)(a);r.__embind_initialize_bindings=()=>(r.__embind_initialize_bindings=G.fd)();var $d=(a,b)=>($d=G.gd)(a,b),ae=()=>(ae=G.hd)(),be=a=>(be=G.id)(a);r.dynCall_viji=(a,b,c,e,f)=>(r.dynCall_viji=G.kd)(a,b,c,e,f);r.dynCall_vijiii=(a,b,c,e,f,k,l)=>(r.dynCall_vijiii=G.ld)(a,b,c,e,f,k,l);r.dynCall_viiiiij=(a,b,c,e,f,k,l,m)=>(r.dynCall_viiiiij=G.md)(a,b,c,e,f,k,l,m);r.dynCall_jii=(a,b,c)=>(r.dynCall_jii=G.nd)(a,b,c);
r.dynCall_vij=(a,b,c,e)=>(r.dynCall_vij=G.od)(a,b,c,e);r.dynCall_iiij=(a,b,c,e,f)=>(r.dynCall_iiij=G.pd)(a,b,c,e,f);r.dynCall_iiiij=(a,b,c,e,f,k)=>(r.dynCall_iiiij=G.qd)(a,b,c,e,f,k);r.dynCall_viij=(a,b,c,e,f)=>(r.dynCall_viij=G.rd)(a,b,c,e,f);r.dynCall_viiij=(a,b,c,e,f,k)=>(r.dynCall_viiij=G.sd)(a,b,c,e,f,k);r.dynCall_ji=(a,b)=>(r.dynCall_ji=G.td)(a,b);r.dynCall_iij=(a,b,c,e)=>(r.dynCall_iij=G.ud)(a,b,c,e);r.dynCall_jiiii=(a,b,c,e,f)=>(r.dynCall_jiiii=G.vd)(a,b,c,e,f);
r.dynCall_jiiiiii=(a,b,c,e,f,k,l)=>(r.dynCall_jiiiiii=G.wd)(a,b,c,e,f,k,l);r.dynCall_jiiiiji=(a,b,c,e,f,k,l,m)=>(r.dynCall_jiiiiji=G.xd)(a,b,c,e,f,k,l,m);r.dynCall_iijj=(a,b,c,e,f,k)=>(r.dynCall_iijj=G.yd)(a,b,c,e,f,k);r.dynCall_jiji=(a,b,c,e,f)=>(r.dynCall_jiji=G.zd)(a,b,c,e,f);r.dynCall_viijii=(a,b,c,e,f,k,l)=>(r.dynCall_viijii=G.Ad)(a,b,c,e,f,k,l);r.dynCall_iiiiij=(a,b,c,e,f,k,l)=>(r.dynCall_iiiiij=G.Bd)(a,b,c,e,f,k,l);
r.dynCall_iiiiijj=(a,b,c,e,f,k,l,m,q)=>(r.dynCall_iiiiijj=G.Cd)(a,b,c,e,f,k,l,m,q);r.dynCall_iiiiiijj=(a,b,c,e,f,k,l,m,q,x)=>(r.dynCall_iiiiiijj=G.Dd)(a,b,c,e,f,k,l,m,q,x);function Vd(a,b,c,e,f){var k=ae();try{P.get(a)(b,c,e,f)}catch(l){be(k);if(l!==l+0)throw l;$d(1,0)}}function Nd(a,b,c){var e=ae();try{return P.get(a)(b,c)}catch(f){be(e);if(f!==f+0)throw f;$d(1,0)}}function Td(a,b,c){var e=ae();try{P.get(a)(b,c)}catch(f){be(e);if(f!==f+0)throw f;$d(1,0)}}
function Md(a,b){var c=ae();try{return P.get(a)(b)}catch(e){be(c);if(e!==e+0)throw e;$d(1,0)}}function Sd(a,b){var c=ae();try{P.get(a)(b)}catch(e){be(c);if(e!==e+0)throw e;$d(1,0)}}function Od(a,b,c,e){var f=ae();try{return P.get(a)(b,c,e)}catch(k){be(f);if(k!==k+0)throw k;$d(1,0)}}function Yd(a,b,c,e,f,k,l,m,q,x){var y=ae();try{P.get(a)(b,c,e,f,k,l,m,q,x)}catch(B){be(y);if(B!==B+0)throw B;$d(1,0)}}function Ud(a,b,c,e){var f=ae();try{P.get(a)(b,c,e)}catch(k){be(f);if(k!==k+0)throw k;$d(1,0)}}
function Xd(a,b,c,e,f,k,l){var m=ae();try{P.get(a)(b,c,e,f,k,l)}catch(q){be(m);if(q!==q+0)throw q;$d(1,0)}}function Pd(a,b,c,e,f){var k=ae();try{return P.get(a)(b,c,e,f)}catch(l){be(k);if(l!==l+0)throw l;$d(1,0)}}function Qd(a,b,c,e,f,k,l){var m=ae();try{return P.get(a)(b,c,e,f,k,l)}catch(q){be(m);if(q!==q+0)throw q;$d(1,0)}}function Wd(a,b,c,e,f,k){var l=ae();try{P.get(a)(b,c,e,f,k)}catch(m){be(l);if(m!==m+0)throw m;$d(1,0)}}
function Rd(a,b,c,e,f,k,l,m,q,x){var y=ae();try{return P.get(a)(b,c,e,f,k,l,m,q,x)}catch(B){be(y);if(B!==B+0)throw B;$d(1,0)}}var ce;Va=function de(){ce||ee();ce||(Va=de)};
function ee(){function a(){if(!ce&&(ce=!0,r.calledRun=!0,!Ga)){db(Oa);aa(r);if(r.onRuntimeInitialized)r.onRuntimeInitialized();if(r.postRun)for("function"==typeof r.postRun&&(r.postRun=[r.postRun]);r.postRun.length;){var b=r.postRun.shift();Pa.unshift(b)}db(Pa)}}if(!(0<Ta)){if(r.preRun)for("function"==typeof r.preRun&&(r.preRun=[r.preRun]);r.preRun.length;)Qa();db(Na);0<Ta||(r.setStatus?(r.setStatus("Running..."),setTimeout(function(){setTimeout(function(){r.setStatus("")},1);a()},1)):a())}}
if(r.preInit)for("function"==typeof r.preInit&&(r.preInit=[r.preInit]);0<r.preInit.length;)r.preInit.pop()();ee();


  return moduleArg.ready
}

);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = CanvasKitInit;
else if (typeof define === 'function' && define['amd'])
  define([], () => CanvasKitInit);
