# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Prepare and archive app"
  lane :prepare  do |options|
    sh("flutter", "build", "ios")
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    enable_automatic_code_signing

    # sh("flutter", "packages", "get")
    # sh("flutter", "clean")
    sh("flutter", "build", "ios")

    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner"
    )

    api_key = app_store_connect_api_key(
      key_id: "8H848U5TNL",
      issuer_id: "69a6de90-44a3-47e3-e053-5b8c7c11a4d1",
      key_filepath: "/Users/rodydavis/Developer/Github/forks/flutter_piano/ios/fastlane/AuthKey_8H848U5TNL.p8",
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
    )
    
    pilot(
      skip_waiting_for_build_processing: true,
      api_key: api_key
    )
  end

  desc "Push a new release build to the App Store"
  lane :release do  
    enable_automatic_code_signing

    # sh("flutter", "packages", "get")
    # sh("flutter", "clean")
    # sh("flutter", "build", "ios")
    
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner"
    )

    api_key = app_store_connect_api_key(
      key_id: "8H848U5TNL",
      issuer_id: "69a6de90-44a3-47e3-e053-5b8c7c11a4d1",
      key_filepath: "/Users/rodydavis/Developer/Github/forks/flutter_piano/ios/fastlane/AuthKey_8H848U5TNL.p8",
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
    )

    deliver(
      submit_for_review: true,
      automatic_release: true,
      skip_screenshots: true,
      force: true,
      skip_waiting_for_build_processing: true,
      api_key: api_key
    )
  end
end