name: Publish example and package

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'master'

      - name: Install
        run: flutter pub get

      - name: Build Example
        run: flutter build web && cd ..

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1.3

      - name: Build Docs
        run: dart doc -o build/web/docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
